### ISSUE TITLE
Cannot shadow gatsby-theme-try-ghost/src/utils/fragments.js

### ISSUE THREAD

**Issue by savyajha** [styxlab/gatsby-theme-try-ghost#104]
I'm unable to shadow `gatsby-theme-try-ghost/src/utils/fragments.js`. I've created `<site-name>/src/gatsby-theme-try-ghost/utils/fragments.js` which differs thus:
```
@@ -166,16 +166,6 @@ export const ghostPostFields = graphql`
             tableOfContents
         }
 
-        # ImgSharp
-        featureImageSharp {
-            base
-            childImageSharp {
-                fluid(maxWidth: 1040) {
-                    ...GatsbyImageSharpFluid
-                }
-            }
-        }
-
     }
 `
 
@@ -278,15 +268,6 @@ export const ghostPageFields = graphql`
             tableOfContents
         }
 
-        # ImgSharp
-        featureImageSharp {
-            base
-            childImageSharp {
-                fluid(maxWidth: 1040) {
-                    ...GatsbyImageSharpFluid
-                }
-            }
-        }
     }
 `
 
@@ -313,15 +294,5 @@ export const ghostSettingsFields = graphql`
             label
             url
         }
-
-        # ImgSharp
-        coverImageSharp {
-            base
-            childImageSharp {
-                fluid(quality: 90, maxWidth: 1920) {
-                    ...GatsbyImageSharpFluid
-                }
-            }
-        }
     }
 `
```
Unfortunately whenever I try to run `gatsby develop` I get this issue: `Found two different GraphQL fragments with identical name "GhostPostFields". Fragment names must be unique`.

However, if I apply these differences to the original file in `<site-name>/node_modules/gatsby-theme-try-ghost/src/utils/fragments.js` then it works.

**Comment by styxlab** [comment]
You cannot shadow `fragments.js` but if you are trying to solve #97 shadowing is the wrong direction. You should write a custom schema for `featureImageSharp` or else import at least one dummy picture, so the schema is automatically inferred. Note that I generally cannot answer questions related to Gatsby, React or GraphQL - there are discussion groups at Gatsby that you can use for that.

**Comment by savyajha** [comment]
I realise that now.

I was, and I think I've understood how. Unfortunately, as I said, I'm not a programmer so there's a lot of stumbling around for me to do. Thanks for your help. :)
