### ISSUE TITLE
In-page footnote links lead to linked part getting hidden behind header

### ISSUE THREAD

**Issue by savyajha** [styxlab/gatsby-theme-try-ghost#107]
**Problem:** If I click on a footnote, I expect to be taken to the text of the footnote itself, but the text gets hidden behind the floating header. This doesn't happen with the table of contents which the toc plugin of this theme provides.

**Example:** On [this page on my blog](https://hawkradius.com/thoughts-on-glimpses-of-world-history-by-nehru-part-5/), we have various footnotes. An example would be the [first footnote](https://hawkradius.com/thoughts-on-glimpses-of-world-history-by-nehru-part-5/#fn1). However, if you go to the first footnote you'll see it gets hidden behind the header strip.

An example which gets it right (using headings, not footnotes) is the jamify.org blog. For example [this link from jamify](https://www.jamify.org/2020/05/19/getting-started-with-jamify/#deploy-the-jamify-starter) goes to the linked heading without it getting hidden behind the header strip.

Any chance of getting the same behaviour for footnotes as well?

**Caveat:** I see the same behaviour for footnotes in the default Casper theme.

**Comment by styxlab** [comment]
This can be solved with a plugin that takes care of footnote links, exactly as [gatsby-theme-ghost-toc](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-toc) is doing it with the `activeHash` function.

**Comment by styxlab** [comment]
Closing as answered.
