### ISSUE TITLE
Feature images not shown

### ISSUE THREAD

**Issue by styxlab** [styxlab/gatsby-theme-try-ghost#12]
It's great news!!! Just tried it. There is an issue on the featured image. Featured image in desktop version disappears, but in the mobile version is fine. Let me show you:

- Origin live preview: https://jmp.sh/soV3pDW
- Gatsby on the desktop version (featured image disappears): https://jmp.sh/yHfaxBw
-  Gatsby on the mobile version (featured image is fine): https://jmp.sh/a4wJ3sZ

This is my repo details:

- This is my ghost app --> https://m4.azurewebsites.net/
- This is gatsby-starter-try-ghost@1.2.5 deploy --> https://build-b9b072a2-8373-4111-b573-48c581acc841.gtsb.io/
- Ghost Azure deploy --> https://github.com/novogeek/Ghost-Azure/blob/master/README.md

Gatsby cloud log show some issue: 
```
(node:6700) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

The GraphQL query in the non-page component "/usr/src/app/www/node_modules/gatsby-theme-try-ghost/src/templates/page.js" will not be run.

code block or inline code language not specified in html. applying generic code block
```

If you need, here is content and url api:
- Content Api: 0374abf9f73c2b6d111f234d28
- Url api: https://m4.azurewebsites.net

_Originally posted by @KontenaIndonesia in https://github.com/styxlab/gatsby-theme-try-ghost/issues/10#issuecomment-600637350_

**Comment by styxlab** [comment]
You seem to be using a custom theme in connection with additional global css styles that you provided in `codeinjection_styles` in the Ghost admin interface. When I remove those styles, all feature pictures are shown.

While this repo tries to use additional styling provided in the `codeinjection` fields, it may not always work as expected. The reason is that React handles styling a bit different from what you would expect from a traditional website and it is not recommend to add substantial styling in those fields. Especially if those styles are manipulated with client javascript code, this may not work as expected.

If you want to have a new theme style other than the default Casper theme provided here, then this would be best accomplished by shadowing some components and by changing some global styles. Most importantly, everything that is done with javascript scripts should be moved to the React components. You are now on your own :wink:

**Comment by KontenaIndonesia** [comment]
It means, I have to put the custom code into their global or default .scss file, not into header admin. Is it correct? 

Thanks for your help bro :)

**Comment by styxlab** [comment]
You can probably leave the css code in `codeinjection_styles`. The `feature_images` are not shown because you have a `display: none` on the image class that this project is using. In addition, the opacity styling does not work well with `gatsby-images`. 

I suspect that you use a different Ghost template in your original project in conjunction with additional javascript. In summary, getting your theme/css/javascript additions to work with this project, there is more to it than adjusting the css styles or moving it to another location.

I'm closing this issue as I do not provide support for custom styling here. If you want to discuss this further, contact me over this [Contact Form](https://atmolabs.org/contact/).
