### ISSUE TITLE
Removing Date From Post Url 

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#120]
Hi, @styxlab How to remove date from post url ? If you see ghost demo site post url is like : https://demo.ghost.io/admin-settings/

But in jamify.org Post url contains date also, https://www.jamify.org/2020/05/12/add-comments-with-commento/

**Comment by styxlab** [comment]
@amaljithev Thanks for considering to use this project. 

If you begin by using the [Jamify starter](https://www.jamify.org/2020/05/19/getting-started-with-jamify/#build-preview) the default are URLs without date as can be seen on this project's [Demo](https://demo.jamify.org/), e.g. [https://demo.jamify.org/admin-settings/](https://demo.jamify.org/admin-settings/]).

[Jamify.org](https://www.jamify.org/) uses the [advanced routing](https://www.jamify.org/2020/04/28/routing-with-jamify/) feature to include the date, but this needs to be configured and is not the standard.

**Comment by amaljithev** [comment]
@styxlab One more thing, is it possible to add a drop-down menu on nav bar ?

**Comment by styxlab** [comment]
The Gatsby front-end of this project replicates the default Ghost Casper theme. This theme does not have a drop-down menu on nav bar, it only has a *secondary navigation* option which is also supported here.

If you want to make your own customizations, you can best do that with component shadowing. There is a section in the [Jamify tutorials](https://www.jamify.org/) that describes the approach in the context of [customizing the ToC plugin](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/#customize-styling). You can use the same idea for your own theme customizations.
