### ISSUE TITLE
Can I add disqus or other comment widget?

### ISSUE THREAD

**Issue by KontenaIndonesia** [styxlab/gatsby-theme-try-ghost#14]
Thanks for this repo. My site is live now. This repo is absolutely working!

Can I add disqus or something else to make visitor leave a comment?

**Comment by styxlab** [comment]
Thanks a lot for your positive feedabck :smile:

This repo does not yet ship with a commenting system and also has no native support for it. However, you can integrate such a system like you would with any other Gatsby site. There is a great guide on [Adding Comments](https://www.gatsbyjs.org/docs/adding-comments/) that should get you started quickly.

If you get it to work on your site, please consider to contribute to this project by sending a PR. I will likely add a commenting system to this repo in the future. It should be a plugin (so people can opt-in/opt-out) and it should give some choice about the commenting system it integrates (no vendor lock-in).

**Comment by styxlab** [comment]
Today I'm happy to announce [gatsby-theme-ghost-commento](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-commento) which lets you easily add the commenting system [Commento](https://commento.io/) to your website. Commento is a good fit for Gatsby-Ghost blogs.

As most commenting systems work by embedding a simple JavaScript file into your page, the new `gatsby-theme-ghost-commento` plugin can be adapted for integrating other systems like Disqus, Facebook Comments, Gitalk, Isso, Schnack, TalkYard or Remark42.
