### ISSUE TITLE
gatsby-rehype-inline-image throws error even if gatsby-plugin-sharp should work fine

### ISSUE THREAD

**Issue by tobimori** [styxlab/gatsby-theme-try-ghost#143]
```
ERROR 
Gatsby-plugin-sharp wasn't setup correctly in gatsby-config.js. Make sure you add it to the plugins array.
```

Source code is [here](https://github.com/ShortTechDE/ingenious-gatsby/tree/rehype).

**Comment by styxlab** [comment]
@tobimori: Good to see you here and thanks for catching this. I'll update the README.

**Comment by tobimori** [comment]
That's unfortunately not solving my problem. `gatsby-plugin-sharp` is being loaded in `gatsby-config.js` and is installed too.

**Comment by styxlab** [comment]
There is no problem, if you update to the latest `gatsby-plugin-sharp` version :grinning:

```
git clone https://github.com/ShortTechDE/ingenious-gatsby.git
cd ingenious-gatsby
git checkout rehype
yarn add gatsby-plugin-sharp
gatsby build
```

is not showing the above error (there are some other issues that need fixing though.)

**Comment by tobimori** [comment]
Thanks, that fixed it.
