### ISSUE TITLE
twitter:image won't be shown by Twitter cards due to robots.txt when Ghost site is set to private

### ISSUE THREAD

**Issue by tobimori** [styxlab/gatsby-theme-try-ghost#144]
![bug](https://user-images.githubusercontent.com/29142128/86277187-8d863600-bbd6-11ea-9c48-1bbf3a7dae44.png)

A workaround is to use my [headless-placeholder](https://github.com/ShortTechDE/headless-placeholder) Ghost theme, which allows indexing by search engines for image folders and redirects to a site of your choice when accessed normally. The site shouldn't be set to be private then, tho.

![fixed with theme](https://user-images.githubusercontent.com/29142128/86277270-b8708a00-bbd6-11ea-91e8-d8eaffcdc78a.png)

**Comment by styxlab** [comment]
I don't think this is a problem when built with `gatsby-theme-try-ghost` at least if you use the latest version of `gatsby-plugin-ghost-images` which also sources in meta images:

![image](https://user-images.githubusercontent.com/19638263/86289766-8a964000-bbec-11ea-8362-c2ee17708e68.png)

![image](https://user-images.githubusercontent.com/19638263/86290116-2c1d9180-bbed-11ea-8d7a-0e99e92e1060.png)

**Comment by tobimori** [comment]
If that's true, there might be another problem:

When the site is recompiled, the url of the linked image changes and Twitter still tries to access the old url, resulting in a broken embed until the cache is deleted by revalidating in the card validator.

That's why I switched those urls back to the cms, not the ones Gatsby sources.

Also, did you think about the possibility to set an image for OpenGraph meta and another one for Twitter meta? Ghost allows that but I'm not sure if this theme supports it.

**Comment by styxlab** [comment]
> When the site is recompiled, the url of the linked image changes and Twitter still tries to access the old url, resulting in a broken embed until the cache is deleted by revalidating in the card validator.

If the image does not change, recompiling should not change the url of the image. Could you show a reproduced example of that?

> Also, did you think about the possibility to set an image for OpenGraph meta and another one for Twitter meta? Ghost allows that but I'm not sure if this theme supports it.

Yes, this is already supported in `gatsby-theme-try-ghost`:

![image](https://user-images.githubusercontent.com/19638263/86296181-807a3e80-bbf8-11ea-98cb-88eb3640668b.png)

You have to place the image in your `src/images` and call it `site-meta.png` though.

**Comment by tobimori** [comment]
For Jamify, it seems like you use a direct link to Unsplash rather than leaving the images on the CMS or letting Gatsby import them. I'll test my guess later.

**Comment by tobimori** [comment]
I can confirm that the demo site still links to the cms server/content folder and does not link to the processed image.

**Comment by styxlab** [comment]
It's true that the meta images for post pages are served from a direct link (or from the cms, if pictures are uploaded):

![image](https://user-images.githubusercontent.com/19638263/86337647-ae3fa180-bc51-11ea-9048-4ac6b53ddc1a.png)

I will change that in the next version, so they get served exactly as the ones from the index page:

![image](https://user-images.githubusercontent.com/19638263/86337351-47ba8380-bc51-11ea-9f8e-7386d6527ab0.png)

I will keep this issue open until the new changes are merged. Thanks!

**Comment by styxlab** [comment]
All meta images should now refer to local images, if available. External images are still used as fallback.
