### ISSUE TITLE
gatsby-plugin-feed

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#159]
To Reproduce, 

https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/   

In Step : [jamify-starter]$ yarn build  , Following errors are thrown, 

![1](https://user-images.githubusercontent.com/33357428/88452662-2fb7d780-ce7e-11ea-87cf-c0c7c17993b3.png)

**Comment by amaljithev** [comment]
@styxlab

**Comment by styxlab** [comment]
What content API key are you using?

**Comment by amaljithev** [comment]
I installed Ghost in localhost. I'm using that content api

**Comment by styxlab** [comment]
I repeated all steps described in

https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/

and everything builds without errors, so I am not able to reproduce the issue. 

- Could you please describe all steps in details that lead to the shown error? 
- Does the error also occur with a fresh ghost install? 
- Did you import custom content?

Thanks for reporting and following up on this!

**Comment by styxlab** [comment]
@amaljithev: Could you please publish your solution here, so other user's who run into the same issue know how to solve it?

**Comment by amaljithev** [comment]
Your solution worked for me. @styxlab 
yarn clean
yarn build
