### ISSUE TITLE
gatsby-transformer-rehype detects MarkdownBody but not html in MarkdownRemark

### ISSUE THREAD

**Issue by basnetsoyuj** [styxlab/gatsby-theme-try-ghost#161]
I have been trying to use **gatsby-transformer-rehype** to generate **Table of Contents** for my personal website.
Instead of GhostPages, it uses the plain old Markdown using the **gatsby-transformer-remark** plugin that makes **MarkdownRemark** entry in graphql.

The following code does not work:
```
{
      resolve: `gatsby-transformer-rehype`,
      options: {
        // Condition for selecting an existing GrapghQL node (optional)
        // If not set, the transformer operates on file nodes.
        filter: node => node.internal.type === `MarkdownRemark`,
        // Only needed when using filter (optional, default: node.html)
        // Source location of the html to be transformed
        source: node => node.html,
        // Additional fields of the sourced node can be added here (optional)
        // These fields are then available on the htmlNode on `htmlNode.context`
        contextFields: [],
        // Fragment mode (optional, default: true)
        fragment: true,
        // Space mode (optional, default: `html`)
        space: `html`,
        // EmitParseErrors mode (optional, default: false)
        emitParseErrors: false,
        // Verbose mode (optional, default: false)
        verbose: false,
        // Plugins configs (optional but most likely you need one)
        plugins: [],
      },
    },
```

However after changing the option to :
`        source: node => node.rawMarkdownBody`

I can access it using **internal.content**.

How do I use it with HTML generated from **gatsby-transformer-remark**?

**Comment by styxlab** [comment]
@basnetsoyuj Thanks for your interest in this project. Could you please setup an example repo that I can use for reproduction and testing?

**Comment by basnetsoyuj** [comment]
I have setup an example repo here: https://github.com/basnetsoyuj/gatsby-casper

I have created two branches to show two different cases: **master** and **dev**

In the master branch:
when I use `source: node => node.rawMarkdownBody`
![Frame 2](https://user-images.githubusercontent.com/18349557/89096860-8763bf00-d3f9-11ea-8a02-85c4372578b9.png)

it gives the Table Of Contents. But since it is using raw markdown string rather than HTML, it only detects header tags and not "#"


In the dev branch:
So I tried using it with HTML rather than raw markdown:
![Frame 1](https://user-images.githubusercontent.com/18349557/89096917-00fbad00-d3fa-11ea-8d9f-5343e7e2a446.png)

But now for some reason, it does not display any ToC and we can even see that **internal.content** is null. So there is some problem configuring the **gatsby-transformer-rehype** with HTML generated from **gatsby-transformer-remark**


Note that **node.html** and **node.rawMarkdownBody** are in the same hierarchical structure:
![Annotation 2020-08-01 131611](https://user-images.githubusercontent.com/18349557/89096978-83846c80-d3fa-11ea-8c81-96c88dbcde00.png)

**Comment by styxlab** [comment]
Problem is that **gatsby-transformer-rehype** finds an empty "html" field, because **gatsby-transformer-remark** hasn't finished building it, whereas the `rawMarkdownBody` is available earlier as it does not have to be processed. You are requiring a dependency, but since we are dealing with async processes, this is not possible. You would have to run  **gatsby-transformer-rehype**  as a sub-plugin of **gatsby-transformer-remark**, but this won't work as both plugins have not been designed for that.

However, I am wondering why you want to use **gatsby-transformer-rehype** for creating a ToC, because  **gatsby-transformer-remark** also produces a ToC - so there is no need for this plugin in the first place.

**Comment by basnetsoyuj** [comment]
My markdown file can contain both HTML as well as markdown, but the built-in ToC generator of the **gatsby-transformer-remark** works only for "#" and not the tags. So I wanted to convert the end result (HTML) as a whole to a ToC.

Moreover, I'm trying to implement your gatsby try ghost ToC, so it would be much easier with **gatsby-transformer-rehype** as the ToC generated by **gatsby-transformer-remark** is not in the same format.

![image](https://user-images.githubusercontent.com/18349557/89098512-137ce300-d408-11ea-8ce9-b847109928e7.png)

I just got started with Gatsby and React. I'm sorry to bother you!

**Comment by styxlab** [comment]
Looks like you can only accomplish this by writing your own plugin. You could write a sub-plugin for `gatsby-transformer-remark` that generates the ToC as you want.

Alternatively, you could write a `gatsby-transformer-remark` sub-plugin that creates a new node after it has generated the `html`. `gatsby-transformer-rehype` would then be able to pick up the `html` on that new node.

**Comment by basnetsoyuj** [comment]
Thank you for your help! :)
