### ISSUE TITLE
MultiAuthor Post

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#162]
In Multi Author Posts , Only One Author Name Is Getting Displayed.

Steps To Reproduce : Add two authors for a post. 

Both author icon are present. But only one of the author name is getting displayed. (It should be Author1,Author2)

Also inside the post, its displayed as AUTHOR1AUTHOR2 - without space or comma @styxlab

**Comment by styxlab** [comment]
@amaljithev: Thanks for reporting. Will look into it.

**Comment by styxlab** [comment]
Confirmed. Will be fixed in next release.

**Comment by styxlab** [comment]
Should be fixed in latest versions. During development I found another bug with scrambled ordering of authors and tags originating in the source plugin that I also fixed along the way. Please test and close after verifying.

**Comment by amaljithev** [comment]
Okay I will test 👍
