### ISSUE TITLE
[gatsby-theme-ghost-members] plugin: Add option for mailchimp API backend

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#163]
Although Ghost CMS on localhost has great advantages, it comes with (of course) with certain limitations , one is subscription and newsletter. I think this can be handled by integrating with mailchimp . #FeatureRequest

**Comment by styxlab** [comment]
Sure, I think I mention these limitations in the article [Running a professional blog for free](https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/). Can mailchimp also take care of the signup procedure (sending initial mails, confirming subscriptions, sending unsubscribe links with every mail, etc.)?

**Comment by amaljithev** [comment]
Yes , Please see, https://gatsby-casper.netlify.app

**Comment by amaljithev** [comment]
Yes

**Comment by styxlab** [comment]
If that's the case, then I am in favor of enhancing the [gatsby-theme-ghost-members](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-members) plugin with a mailchimp option. I don't have development capacity for this at the moment, but would be happy to act as a sparring partner if you (or someone else you bring to this project) want to take on the development.

**Comment by styxlab** [comment]
I close this for now. I'll open it up again, once someone shows interest in developing this feature which I think would be a great addition to gatsby-theme-ghost-members plugin.
