### ISSUE TITLE
how to component shadow layout.js (noob question)

### ISSUE THREAD

**Issue by nowestsun** [styxlab/gatsby-theme-try-ghost#164]
Hi, i would like to edit the site footer, e.g. to insert a link to my Instagram page. How do I do it? Do I need to component shadow the layout.js? I tried to do it, but it returned "multiple root queries" error while running gatsby develop. Similar question on inserting an Instagram link to the header. Which file should I edit?

Sorry for the noob question, complete newbie here.. Thanks.

**Comment by styxlab** [comment]
I recommend reading the [Gatsby docs on component shadowing](https://www.gatsbyjs.org/docs/themes/shadowing/) and once you feel familiar with the concept and simple examples you may want to read [Adding a table of conents](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/) where I describe how to use component shadowing in this project.

**Comment by nowestsun** [comment]
Thanks for your reply styxlab 👍. I have read the recommended docs.

Correct me if I'm wrong, to use component shadowing to edit the site footer in "my_site\node_modules\gatsby-theme-try-ghost\src\components\common\Layout.js", I just need to copy the Layout.js to "my_site\src\gatsby-theme-try-ghost\components\common", and edit the corresponding lines in the copied Layout.js to add an Instagram link for example?

However, when I do this, I get the following error after running gatsby develop:
-----------------------
Multiple "root" queries found: "GhostSettings" and "GhostSettings".
Only the first ("GhostSettings") will be registered.

Instead of:

   1 | query GhostSettings {
   2 |   allGhostSettings {
   3 |     #...
   4 |   }
   5 | }
   6 | 
   7 | query GhostSettings {
   8 |   allGhostSettings {
   9 |     #...
  10 |   }
  11 | }

Do:

  1 | query ghostSettingsAndGhostSettings {
  2 |   allGhostSettings {
  3 |     #...
  4 |   }
  5 |   allGhostSettings {
  6 |     #...
  7 |   }
  8 | }

This can happen when you use two page/static queries in one file. Please combine those into one query.
If you're defining multiple components (each with a static query) in one file, you'll need to move each component to its own file.

File: node_modules\gatsby-theme-try-ghost\src\components\common\Layout.js
-----------------------

Appreciate your advice on this, thanks a lot!

**Comment by styxlab** [comment]
Could you please publish your example on github, so I can clone and try to reproduce your issue?

**Comment by nowestsun** [comment]
Hi,

Please find the link here:
[https://github.com/nowestsun/jamify-demo](url)

Thank you

**Comment by styxlab** [comment]
Please find a new pull request in your repo. Merging these changes should fix your issues:

1. GraphQL query names must be different in shadowing file.
2. Paths to existing files must be changed, so they can be found from the shadowing file.

**Comment by nowestsun** [comment]
thank you very much! issue solved! 👍
