### ISSUE TITLE
gatsby-plugin-feed Build fail when posts have no images.

### ISSUE THREAD

**Issue by issa4700** [styxlab/gatsby-theme-try-ghost#165]
When building the site, the build will fail and produce the an error if a post does not have a featured image.
![image](https://user-images.githubusercontent.com/44219189/89837140-3a51bc80-db60-11ea-897f-55b3368e382f.png)

The site successfully builds if *all* posts have a set featured image.

**Comment by styxlab** [comment]
This is not a general problem. Please provide an example for testing, so I can reproduce and analyze locally.

**Comment by styxlab** [comment]
Sorry for the delay. Should be fixed in latest versions.
