### ISSUE TITLE
Navigation Menu Replicating Ghost "Head" fine locally, needs "hard refresh" to replicate it on Netlify....

### ISSUE THREAD

**Issue by eltel** [styxlab/gatsby-theme-try-ghost#169]
So, it was all going so smoothly at the local(host) level - however, after adding new pages to the 'head' and the navigation menu there  - which work fine - I noticed my preview on Netlify wasn't behaving as expected. It's only after a 'hard refresh' (shift +f5) that the frontend/static site replicates the nav-menu from the backend/head. This, obviously, causes all sorts of problems with the PWA where I can't even hard refresh - not that I should have to.

It's just a sketch/outline for a business idea I'm working on at the moment but here's a link to the preview:
https://festive-euler-3e7965.netlify.app/home/

On first load you can see nav links to the 'tag' page which is actually removed from the navbar in the 'head' and, more importantly, you can't see the link to 'TimeTunnel' (our second main page) until you shift + f5 (then 'tag' also disappears, replaced by 'Time-Tunnel'.

As I've no idea what's causing this and appear to be getting no related errors either locally or on Netlify I've no idea what code to post - if anyone can give me any idea as to what's going on - or where I could start to look I'd be very thankful.

PS: I also cleared the cache before deploying on Netlify as that was the only thing I could think of, the problem persists :(

Thanks in advance for any input you may have on this.

Cheers

Terry

**Comment by styxlab** [comment]
Hey Terry, judging from the Lay-out you are not using this project. Maybe you built on gatsby-starter-ghost? If so, please ask for help there. 

You can easily switch to gatsby-startet-try-ghost as a drop-in replacement and I'd be happy to help you in that case.

**Comment by eltel** [comment]
My god, you're right  - sorry I was using yours the other before deciding on the other as I'm more familiar with that methodology and felt more able to customise the front end - copying this question over there now - I'm still undecided which to proceed with, so I may be back :+1: 
Thanks for your time, apologies.

Terry

**Comment by styxlab** [comment]
Sure, no problem!
