### ISSUE TITLE
Changed image files in static, now get gatsby error

### ISSUE THREAD

**Issue by brittersfullers** [styxlab/gatsby-theme-try-ghost#171]
I am brand new to jamstack and have been sailing along with Jamify template... but I changed the logo favicon files and I keep getting this error in gatbsy cloud on deploy. I'm sure I must have just added the files the wrong way or something. If it would be helpful, I would be happy to get some help on this and then write a FAQ article because I am sure other newbies might have the same questions and want to change the logos. 

"gatsby-plugin-feed" threw an error while running the onPostBuild lifecycle:

The "url" argument must be of type string. Received null

'  155 |             serializer = feed.serialize && typeof feed.serialize === "function" ? feed.serialize : serialize;
  156 |             _context2.next = 17;
> 157 |             return serializer(locals);
      |                    ^
  158 | 
  159 |           case 17:
  160 |             rssFeed = _context2.sent.reduce(function (merged, item) {`

From my dev build:

ERROR #11467 

The new node didn't pass validation: child "internal" fails because [child "content" fails because ["content" must be a string]]

**Comment by styxlab** [comment]
I cannot reproduce this error, so in order to be able to help, please provide a  link to the repo that you deployed to Gatsby Cloud. However, if you used [this repo](https://github.com/brittersfullers/gatsby-starter-ghost) then you are using a different project and you should file an issue there.

**Comment by brittersfullers** [comment]
OK, [here is the link to my repo.](https://github.com/brittersfullers/try-ghost). Thanks for checking it out!

**Comment by styxlab** [comment]
Hi again and thanks for the additional info. 

I cloned your repo and when I first delete the `.ghost.json` file the project builds the demo site without issues. That's a good start: it means your changes on the favicon did not break anything!

After recreating your `.ghost.json` the build fails with a bunch of errors but different from the one you reported. The reason for these errors is that your Ghost CMS is currently down, when I open `https://brittanyfuller.ghost.io` in the browser I see the following message:

![image](https://user-images.githubusercontent.com/19638263/91228923-52f9cf00-e729-11ea-8200-582d0fea2fd0.png)

Your Ghost CMS must be up and running for `gatbsy-starter-try-ghost` (aka Jamify) to be able to source in your content. Let me know  when your CMS site is available again. Hopefully, I will then be able to see the above error of the Gatbsy feed plugin.

**Comment by brittersfullers** [comment]
aww yea my ghost trial expired so I started hosting my own version and switched things up. During that process I just decided to uninstall and reinstall the theme and I am not having this issue anymore. I haven't launched my site yet but I'm pretty committed to using jamify (sponsoring the project now!) ... let me know if I can help with any documentation going forward and I'll close this out. @styxlab 👏

**Comment by styxlab** [comment]
Glad to hear it's working now 👍🏻 

I'm really delighted and thankful for your support ❤️ you are the very first to sponsor this project 🎉 

A genuine blog post about Jamify from the users perspective is much needed - it can be about your experience hooking it up, about pitfalls you had to overcome or anything else... no restrictions whatsoever 😊

If you want to discuss topics in more depth, please leave me a contact where I can reach you.
