### ISSUE TITLE
how to customize [newbie]

### ISSUE THREAD

**Issue by leourl** [styxlab/gatsby-theme-try-ghost#172]
first, i want to thank you guys, this is an awesome project, i'm learning a lot from it.

second, i want to ask how do i start to customize this.

i went through this tutorial:
https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/

i got to make it run locally and deployed to netilify successfully, but i'm struggling to customize it.

i want to be able to change things like the navbar color, the font on the posts content and others. i know html, css, and some javascript, but i'm new to react

also, when i change the **Publication Language** in the **Local CMS install** (it is "en" by default) and run "yarn develop", my blog is not rendered, the stuff in the terminal looks good, but nothing appears in the browser.

srry for the english, i'm not good with it

**Comment by styxlab** [comment]
Hi @leourl, welcome and thanks for the encouragement! There is a chapter in the [Adding a table of contents tutorial](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/#customize-styling) where I show how you can use component shadowing to customize styles. This technique can be used to customize literally everything.

With respect to language, this project uses a language file where you need to add your language to: 

https://github.com/styxlab/gatsby-theme-try-ghost/blob/master/packages/gatsby-theme-try-ghost/src/utils/lang.js

You could component shadow this file as well, but if you want to add a new language to the theme, I'd be happy to add it to the package if you provide the translations. Each plugin has a separate `lang.js` file - those have to be translated as well.

**Comment by leourl** [comment]
thanks so much for the attention, i'll study i little more later.
