### ISSUE TITLE
Facebook Removal in header and footer

### ISSUE THREAD

**Issue by JudicialDomicide** [styxlab/gatsby-theme-try-ghost#176]
Hi,

we notice on your website jamify.org you have successfully removed the Facebook icon in the header and also the Facebook link in the footer. Ideally id like to substitute the Facebook icon for a telegram icon and also reflect that in the footer also as we don't use Facebook. in fact I only signed up so that we could resolve the link not going to ghost Facebook. lol.

any guidance on how to modify these would be very useful. We would also want to add privacy policies and other items in the footer and again any understanding of how this can be achieved would be great. We have inspected the source but have struggled to find where the source is as it appears to be being built via Netlify from ghost back end but I'm not sure that can be the case fully as you have added your own customisation with the Jamify text and link in the footer.

**Comment by styxlab** [comment]
Removing or changing Facebook and Twitter links can be done in your Ghost Admin panel, so this can be configured in the headless CMS.

Further customizations have to be done with component shadowing. Have a look at issue #164 where you can find a link to a repo where the footer was customized.

The same technique can be used for the navigation header or any other change you want to make to your layout 😊

**Comment by JudicialDomicide** [comment]
This is really helpful. Thank you very much. I have reviewed the issue mentioned and also Gatsby Shadowing docs. I will have a go myself soon. 
Thanks again.
