### ISSUE TITLE
how to configure compression/quality of featured images

### ISSUE THREAD

**Issue by nowestsun** [styxlab/gatsby-theme-try-ghost#177]
Hi styxlab,

How do I configure the compression ratio/ quality of featured images in each blog post? I would like to reduce the image quality even further to have smaller image file sizes.

Thank you

**Comment by styxlab** [comment]
@nowestsun: You could use component shadowing to overwrite the defaults in the graphql [fragments.js](gatsby-theme-try-ghost/packages/gatsby-theme-try-ghost/src/utils/fragments.js), but I advice against it. Resolutions and image quality settings have been carefully chosen to give the best compromise between visual crispness and performance. If you reduce image quality, it will most likely be noticeable by your visitors.

**Comment by nowestsun** [comment]
@styxlab thanks for your suggestion. in this case i'll shall just leave the settings at their optimised defaults
