### ISSUE TITLE
Feature Request: Add Commento to any kind of theme

### ISSUE THREAD

**Issue by parthp1808** [styxlab/gatsby-theme-try-ghost#180]
I have built my own gatsby theme and trying to add Commento. Directly adding commento script is not working and I am new to gatsby so don't understand much yet.
Can your plugin work in my use case?

**Comment by styxlab** [comment]
The commento plugin integrates into the core project and cannot be used as a standalone plugin. Reason is that the comments section is seamlessly added into the blog UI of this project.

However, the basic building blocks can be reused and integrated into your own project. Once you study the code of the plugin, it will become obvious to you.

**Comment by styxlab** [comment]
Closed as answered.
