### ISSUE TITLE
Using filesystem as content source

### ISSUE THREAD

**Issue by ScottG489** [styxlab/gatsby-theme-try-ghost#181]
Hey @styxlab. I'm just starting to learn Gatsby and I came across your theme and really like it's design and layout. However, I wanted to use this with local storage.

Is there any way that this would be possible? Perhaps by using theme shadowing or some other method to override the defaults?

As a last resort If there is no way to do this via the usual means then I am also open to forking the repo. If I were to do this, do you have any pointers as to how I could modify the theme to support local storage content?

Any help would be appreciated, thanks! :)

P.S. I did come across https://github.com/styxlab/gatsby-theme-try-ghost/issues/7 but I thought it was more appropriate to open a new issue rather than just commenting there.

**Comment by styxlab** [comment]
@ScottG489 Welcome to this project and thanks for your positive feedback!

What do you mean by local storage? A headless Ghost CMS on localhost? Or your own data structures on stored locally?

**Comment by ScottG489** [comment]
Hey @styxlab! Thanks for the quick response.

Yes, I mean the latter of the two. I'd like to write my blog posts in Markdown, checked into source control. This is a fairly common pattern I believe. Specifically, I'd probably be using this plugin:

https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/

I think I'd use this along with the gatsby-transformer-remark plugin.

Anyways, specifics aside I'm hoping that's possible.

What approach (e.g. theme shadowing, etc) would you suggest?

**Comment by styxlab** [comment]
While I like to promote this project, it is probably not a good fit for your use case as it is tailored towards Ghost CMS content. I'd recommend you check out Scott Coopers open-source project [gatsby-casper](https://github.com/scttcper/gatsby-casper) which is a better fit if you want to work with markdown.

**Comment by ScottG489** [comment]
Thanks, I'll take a look. Looks pretty good at first take.

I think I may have came across that project in the [Gatsby plugin library](https://www.gatsbyjs.com/plugins/?=gatsby-theme) but I found the look of yours to be a little more refined as well as having a few more features such as the dark/light mode and the page header following you as you scroll.

In any case, thanks for the help. I'll close this out.
