### ISSUE TITLE
Feature: Add custom theme 'Liebling'

### ISSUE THREAD

**Issue by rajaseg** [styxlab/gatsby-theme-try-ghost#183]
Is it possible to use custom ghost theme? I wanted to have the same look and feel of my back end Ghost (from where we are pulling posts).

**Comment by styxlab** [comment]
@rajaseg: It is not possible to directly use Ghost custom themes with this project. However, with some development effort, it is possible to port any theme to this project and package it as a plugin. I welcome all theme developers who want to port their favourite theme and make it available here!

**Comment by rajaseg** [comment]
Thanks for the reply. I am not full fledged ghost theme developer. But wanted to use Liebling theme. If you are willing to help I forked that theme and started working on it. Please let me know the steps to package it to suit in the current project.

**Comment by styxlab** [comment]
Do you have a private Channel where I can reach you?

**Comment by rajaseg** [comment]
I don't have any private channel? Is it OK to provide you my email ID?
Or else let me know your private channel to contact you?

**Comment by styxlab** [comment]
Sure.

**Comment by rajaseg** [comment]
I have subscribed to https://www.jamify.org Please let me know if anything wrong.

**Comment by styxlab** [comment]
@rajaseg: Sent you an email.

**Comment by styxlab** [comment]
It is not clear at the moment, if this feature can be realized. Issue closed for now. Can be re-opened when development activity started.
