### ISSUE TITLE
use shadowing add gatsby plugin in post.js ，error

### ISSUE THREAD

**Issue by xiyizhou** [styxlab/gatsby-theme-try-ghost#185]
now ,useing gatsby-starter-try-ghost ,
i want to add [gatsby-plugin-valine](https://www.gatsbyjs.com/plugins/gatsby-plugin-valine/?=valine)  as comment system.
the setup is 
1. install the npm package 
`yarn add gatsby-plugin-valine`
2. Add the plugin into the gatsby-config.js script 

> `{
>        resolve: `gatsby-plugin-valine`,
>        options: {
>          appId: `axxxxxxxI`,
>          appKey: `SxxxxxxxxxYp6hJ`,
>          avatar: `robohash`,
>                },
>         },`

3. create path `<my-project>\src\gatsby-theme-try-ghost\templates`
4. copy `post.js` from `gatsby-theme-try-ghost/packages/gatsby-theme-try-ghost/src/templates/` to  `<my-project>\src\gatsby-theme-try-ghost\templates`
5.  import and add the <Valine> component to `post.js`
---
`
...
import { Comments, TableOfContents, Subscribe } from '../components/common'
import Valine from 'gatsby-plugin-valine'

...
const Post = ({ data, location, pageContext }) => {
    const { basePath } = useOptions()
    ...

    return (
       ...
                                <Comments id={post.id}/>

                            </article>
                        </div>
			<Valine />
                    </Layout>
             ....
`
---
6. run `gatsby develop`
**error info is** 
` ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/effects' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/effects' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/helpers' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/helpers' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/meta' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/meta' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/routing' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/routing' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/use-lang' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/use-lang' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/use-options' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/use-options' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

failed Building development bundle - 18.386s
                                                `

**Comment by styxlab** [comment]
You need to adapt your import paths in `src\gatsby-theme-try-ghost\templates\post.js`. Have a look at [gatsby-theme-ghost-commento](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-commento) to see how this is done. For future communications, please always send me a link to a working test example, so I can better analyze what's going on.

**Comment by xiyizhou** [comment]
the repo is [iNote-xyz](https://github.com/xiyizhou/iNote-xyz),  my site is https://inote.xyz, it's still not work

**Comment by xiyizhou** [comment]
hi, even i shadowing post.js in `src\gatsby-theme-try-ghost\templates\post.js,`  not change anything in post.js , the starter is not work also . what  should i do?
` ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/effects' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/effects' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/helpers' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/helpers' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../components/common/meta' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../components/common/meta' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/routing' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/routing' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/use-lang' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/use-lang' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../utils/use-options' in 'C:\inote-xyz\src\gatsby-theme-try-ghost\templates'

If you're trying to use a package make sure that '../utils/use-options' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\gatsby-theme-try-ghost\templates\post.js

failed Building development bundle - 8.757s
                                                  `

**Comment by styxlab** [comment]
As I said before, you must adapt the import paths in the shadowing file `src\gatsby-theme-try-ghost\templates\post.js`.

**Comment by styxlab** [comment]
Hey @xiyizhou: I was going to have a look at [iNote-xyz](https://github.com/xiyizhou/iNote-xyz-jam) but your Ghost CMS cannot be reached on https://cms.inote.xyz.

**Comment by xiyizhou** [comment]
thanks for your reply, now you can check the [repo ](https://github.com/xiyizhou/gatsby-starter-try-ghost) , the [cms ](https://cms.zhiyunnongfu.com/) , and the [gatsby site](https://gatsby-starter-try-ghost.netlify.app/).
i had add the [valine ](https://www.gatsbyjs.com/plugins/gatsby-plugin-valine/?=valine), but  it still not work . because I am not familiar with English and codes.

**Comment by styxlab** [comment]
I sent you a [pull request](https://github.com/xiyizhou/gatsby-starter-try-ghost/pull/1) that should fix the issue. As I initially suspected, you have to adjust the import paths of the shadowing file. The shadowing file must get a proper reference to the original, have a look at the [diff](https://github.com/xiyizhou/gatsby-starter-try-ghost/pull/1/files). Result looks good on first sight:

![image](https://user-images.githubusercontent.com/19638263/94730748-fb700400-0363-11eb-8fd5-feebfe2acb0f.png)

**Comment by xiyizhou** [comment]
now it is work , i learned a lot again at least, very grateful！

**Comment by styxlab** [comment]
You are welcome, cool that it's working now.
