### ISSUE TITLE
Not applying custom theme!

### ISSUE THREAD

**Issue by alesdonoso** [styxlab/gatsby-theme-try-ghost#19]
Hi there Styxlab!

I've used your theme + gatsby + glitch for hosting + surge for deploy as a static website, but I've changed some details on the Casper theme and they are not being applied. On my panel admin, I've uploaded my new Casper theme, it shows correctly on my glitch but not when I deploy with surge in my domain. It keeps the default styles from the casper default eheme.

Any suggestion?

**Comment by styxlab** [comment]
React styling works different from what you would expect from a traditional website where you can simply add some css/js in your head. So, if your site significantly departs from the standard Casper theme and uses jQuery or alike to change styles, you would need to design a new Gatsby React theme as an additional theme plugin to be consumed by this repo.

Nonetheless, all styles provided in the code-injection fields on the Ghost CMS are sourced in and also applied to the head here. Therefore, simple style additions may work, but it is actually neither recommended not supported to make substantial theme changes with CSS in those fields.

While this repo currently does not support any styles different from the standard Casper theme, I can  further look into your issue if you provide me with the Content API keys to your Ghost CMS. I also need some info about the custom theme that you uploaded in Ghost admin.

I plan to provide some instructions about how to customize the standard theme with Gatsby best practices, but it may take some time until that materializes.

**Comment by alesdonoso** [comment]
Thanks for your fast reply styxlab! I really appreciate your support. In that case, we will try to generate a redirect from our glitch to the domain so all the theme will be applied without problems 👍 

I don't think will be possible to apply all the changes I've made in my custom casper theme so I don't want you to lose your time! Thanks 🥇
