### ISSUE TITLE
Secondary navigation not updating on the gatsby part

### ISSUE THREAD

**Issue by GHCat-dev** [styxlab/gatsby-theme-try-ghost#192]
I had followed your tutorial here: https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/ and everything works fine. However when I was playing around the secondary navigation by following this tutorial: https://ghost.org/tutorials/adding-social-network-links/ => this successfully update the Ghost backend with social media icons. 
But when I rebuild the gatsby site, it didn't update the frontend part. Is there a way to change that?
It's hard to imagine I cannot update anything on the frontend, any suggestion?
It's the same when I try to change the "Website" string to something else on /author.
I will appreciate any help @styxlab

**Comment by styxlab** [comment]
If you add secondary navigation in your Ghost CMS, those links should show up in your built Jamify Blog site as text links (exactly the same way as shown in part one of the mentioned Ghost tutorial).

The second part in that tutorial describes how to replace those text links with icons. If you need that, I recommend you use component shadowing to make those adoptions. There is a section in the [Table of contents Tutorial](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/) which describes this approach. With component shadowing, you can customize *everything* on the frontend.

As adapting social links is a common use case, I would very much like to integrate a new plugin into this project, which could simplify this customization to a point where no coding is needed. Anyone interested to start that as a side project?

**Comment by styxlab** [comment]
Closed as answered.
