### ISSUE TITLE
Is there a way to use the subscription button with Netlify form only?

### ISSUE THREAD

**Issue by GHCat-dev** [styxlab/gatsby-theme-try-ghost#193]
I had followed this tutorial: https://www.jamify.org/2020/07/05/newsletter-with-jamify/
However I'm hosting ghost locally, and I would like to use Netlify to make this subscribe button works without making a POST request to the Ghost backend but to netlify.
Any suggestions if this is possible, or maybe to change something on the members plugin?
I will appreciate any help @styxlab.
Thanks,

**Comment by styxlab** [comment]
The functionality you are looking for is already present in [gatsby-theme-ghost-contact](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-contact). So, you could take that as an inspiration to improve the members plugin.

**Comment by styxlab** [comment]
Closed as answered.
