### ISSUE TITLE
Is it possible to change theme?

### ISSUE THREAD

**Issue by correctbuddy789** [styxlab/gatsby-theme-try-ghost#194]
Hy, I was just wondering would it be possible to change theme, while using Jamify. for eg. Instead of Casper I would like to use https://github.com/eddiesigner/liebling/ 
I can upload this using Ghost CMS but as soon as I run Yarn develop/build the output is always with the Casper

**Comment by styxlab** [comment]
@correctbuddy789: Welcome to this project. New themes would need to be developed and provided as new plugins. There have been some previous requests about porting Liebling to this project, see #183 and #77. As indicated before, I would support anyone who wants to make a PR for a new theme plugin.

Nonetheless, porting the Liebling theme to this project is not as easy as it might seem at first glance: 

- All animations/transitions used in the theme would have to be re-implemented in React.
- The CSS framework it uses (less) is not compatible with the postCSS pipeline of the current Ghost theme.
- A concept is needed that makes it easy to update the plugin whenever the original Liebling theme changes.

**Comment by styxlab** [comment]
Closed as answered. Can be re-opened, if needed.
