### ISSUE TITLE
Member only contnent

### ISSUE THREAD

**Issue by marcoSven** [styxlab/gatsby-theme-try-ghost#195]
Have you tried the post access for members only feature? Looks like the content is not available during the build.

**Comment by styxlab** [comment]
Could you please elaborate a bit more on what you are trying to achieve? What's your use case?

**Comment by marcoSven** [comment]
If you enable membership in Ghost, you have the option to restrict posts to members and paid members. If you select one of these restricted options the HTML of the post is not included in the Gatsby build. The idea would be to offer the full Ghost membership features, at least to a certain extend. In my use case, the goal is not to 100% secure the content of a post, but just make it not easily accessible. 

I am not sure if there is a way to get the HTML via the Content API if the post is restricted.

**Comment by styxlab** [comment]
Thanks a lot for the explanation. The documented [Content API](https://ghost.org/docs/api/v3/content/#endpoints) does not have any options for downloading restricted content, so I don't think this is currently possible. Maybe you want to bug the Ghost team about it?
