### ISSUE TITLE
How to customise

### ISSUE THREAD

**Issue by udaya2899** [styxlab/gatsby-theme-try-ghost#197]
I previously used gatsby-starter-try-ghost by @TryGhost but now since this was closer to the original Casper theme in Ghost, shifted to this. 

Earlier in `TryGhost/gatsby-starter-try-ghost`, I found the style to be in the `styles` folder in that project. I also wanted the author details at the bottom of the post and modified the react code accordingly.

I couldn't find the code to actually customize here. The project cloned from styxlab/gatsby-starter-try-ghost is at https://github.com/udaya2899/blog-v2

Please help me find the code that actually makes the graphql call and renders the content. Sorry if this is the wrong place to ask.

**Comment by styxlab** [comment]
Welcome to this project @udaya2899!  I suggest that you read the [tutorials](https://www.jamify.org) first, especially the one on [adding a table of contents](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/) as it describes how to customize the style and functionality of the ToC. 

More generally speaking if you want to customize [gatsby-starter-try-ghost](https://github.com/styxlab/gatsby-starter-try-ghost) the right way to do it is with Gatsby [component shadowing](https://www.gatsbyjs.com/blog/2019-04-29-component-shadowing/) for both styles and code. The mentioned ToC article describes how to apply this concept to this project.

The graphql calls you are looking for are bundled in [gatsby-theme-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-try-ghost) which is imported by the starter. Component shadowing lets you define new code in the work directory of the starter that overwrites/shadows the code that you imported by the theme package.

**Comment by udaya2899** [comment]
Thanks! Amazing repo. I'd love to build a port of the [Liebling](https://github.com/eddiesigner/liebling) theme. Would be great if you can guide me on how to start and proceed.

**Comment by styxlab** [comment]
I made some comments about porting Liebling on #194.

**Comment by udaya2899** [comment]
Closing this issue, thanks :)
