### ISSUE TITLE
gatsby-transformer-rehype content null error

### ISSUE THREAD

**Issue by marcoSven** [styxlab/gatsby-theme-try-ghost#200]
The new node didn't pass validation: child "internal" fails because [child "content" fails because ["content" must be a string]]
`"internal": {
        "content": null,
        "type": "HtmlRehype",
        "owner": "gatsby-transformer-rehype"
    }`

To reproduce create an empty page with no content.

**Comment by styxlab** [comment]
This shouldn't happen, but why would you want an empty page with no content?

**Comment by marcoSven** [comment]
I don't want an empty page 😄 - I just noticed it that's all

**Comment by styxlab** [comment]
Cool, I am relieved 😄 A fix is on the way...

**Comment by styxlab** [comment]
Fixed in versions `>= 1.46.2`
