### ISSUE TITLE
Implementing redirects

### ISSUE THREAD

**Issue by code-not-found** [styxlab/gatsby-theme-try-ghost#213]
Hi,

I'm looking into moving my site to Jamify. One of the things I would need to solve is the fact that some of my posts need to support redirects.

It looks like Ghost supports this by [defining a redirects.json](https://ghost.org/tutorials/implementing-redirects/). However I don't think this functionality is currently supported on `styxlab/gatsby-starter-try-ghost` (I tried performing some tests but the redirects did not work).

Any thoughts on the best way to enable this? I also saw that on Gatsby you can [use Actions to achieve redirects](https://www.gatsbyjs.com/docs/actions/#createRedirect).

Thanks in advance for your help.

**Comment by styxlab** [comment]
@code-not-found Thanks for considering the Jamify tools for your next project.

I am not a huge fan of doing redirects in apps. I think redirects are best done on the edge (for Netlify and Amazon you can use plugins). If you are rolling your own servers a reverse proxy like Nginx is a great choice.

**Comment by code-not-found** [comment]
Thanks for the feedback.

I did couple of tests using redirects inside the [Netlify configuration file](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file). This worked flawlessly.
