### ISSUE TITLE
Alternative pageNumber 0

### ISSUE THREAD

**Issue by danielclough** [styxlab/gatsby-theme-try-ghost#23]
How do I get the `pageNumber 0` to show up at `/blog` instead of `/`?
In `/src/gatsby-theme-try-ghost/gatsby-node.js` I have changed to 

```
    paginate({
        createPage,
        items: posts,
        itemsPerPage: postsPerPage,
        component: indexTemplate,
        pathPrefix: ({ pageNumber }) => {
            if (pageNumber === 0) {
                return `/blog`
            } else {
                return `/page`
            }
        },
    })
```

This seems to allow the index at `/src/pages/index.js` to load instead of the ghost pageNumber 0 but it does not display the ghost pageNumber 0 at /blog.

I am having difficulty with styling on my index page.
Not sure if it's a related of separate issue.

**Comment by styxlab** [comment]
I think the recommended way is described in the Gatsby tutorial [Adding a path prefix](https://www.gatsbyjs.org/docs/path-prefix/).

As I have not payed attention to the implementation details of `pathPrefix` I don’t expect it to work with this repo yet. Am happy to take a PR if you want to incorporate  this.

**Comment by danielclough** [comment]
[Here is an example](https://github.com/danielclough/DanielC.US-Gatsby/blob/master/gatsby-node.js) of the Gatsby Starter Ghost with one change in gatsby-node.js - the one mentioned above.

You can see the change here at https://wonderful-archimedes-010c15.netlify.com/blog/
And, you can see that [root](https://wonderful-archimedes-010c15.netlify.com/) is 404, for now.

**Comment by styxlab** [comment]
Your example is referencing *another repo*, so maybe it's best to place your question there? I'm not quite sure I understand what you are trying to achieve, but if you want to change routing, I'd be surprised if it can be accomplished by just changing a couple of code lines. I may be wrong though. Relevant tutorials are:

- [Adding a path prefix](https://www.gatsbyjs.org/docs/path-prefix/)
- [Gatsby Routing](https://www.gatsbyjs.org/docs/routing/)

As this space is not intended for problems related to individual customizations, I hope you understand that I won't be able to provide any further support on this topic.

**Comment by danielclough** [comment]
No problem.
I don't need help because I can use the other repository with the one line
change described.
I was just letting you know how it works.

**Comment by styxlab** [comment]
Thanks for reporting back. Then it should work here as well.

**Comment by danielclough** [comment]
I have made an example showing the desired result with your repo by changing it in the file at `/node-modules/gatsby-theme-try-ghost/gatsby-node.js` in the way described above.

When in the node-modules folder it works to change the the theme `pageNumber 0` to `/blog` but when I shadow the file to /src/gatsby-theme-try-ghost/gatsby-node.js - it still doesn't work.
