### ISSUE TITLE
Don't work gatsby-theme-ghost-toc

### ISSUE THREAD

**Issue by motherfacker** [styxlab/gatsby-theme-try-ghost#242]
Hi
1. I clone my git "gatsby-starter-try-ghost" and cd 
2. yarn add gatsby-theme-try-ghost, gatsby-transformer-rehype, gatsby-theme-ghost-toc
3. edit gatsby-config.js (maybe i put code in wrong place)
4. add commit and push git

all steps are succeed but my blog post don't changes. Waht i do wrong? Or how it works?
Help me pls i am newbie
Thanks!

my repo https://github.com/motherfacker/gatsby-theme-try-ghost

**Comment by styxlab** [comment]
Welcome! 

If you are starting from `gatsby-starter-try-ghost` (which is recommended) you must not add `gatsby-theme-try-ghost` as this package is already included in the starter. Adding the toc theme is described in the tutorial article [Adding a table of contents](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/).

**Comment by motherfacker** [comment]
> Welcome!
> 
> If you are starting from `gatsby-starter-try-ghost` (which is recommended) you must not add `gatsby-theme-try-ghost` as this package is already included in the starter. Adding the toc theme is described in the tutorial article [Adding a table of contents](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/).

What can i do now?
remove all packgase that installed or only "**gatsby-theme-try-ghost**, **gatsby-transformer-rehype**"
or delete **gatsby-starter-try-ghos**t from github and start from begin

**Comment by styxlab** [comment]
I recommend you start from scratch and follow the tutorial.

**Comment by motherfacker** [comment]
> I recommend you start from scratch and follow the tutorial.
> 
> The alternatives are probably more difficult.
> 
> ...and thanks so much for sponsoring ♥️ this project!

It's works on localhost. So now i can add it (jamify-toc) to my github and link with netlify and it's will to work too?
And i can add other plugins (comments, etc.) like this?

You very help me.  I'm just a user but i think it's very cool thing thx you too!

**Comment by styxlab** [comment]
Great. Yes, this should work. Plugins from the plugin list in the README should work out of the box. Deploys to Netlify are also described in the [tutorials](www.jamify.org).
