### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by motherfacker** [styxlab/gatsby-theme-try-ghost#243]
Hi
i read [tutorial](https://www.jamify.org/2020/04/21/adding-a-table-of-contents/) that you recomend and try to use component shadowing to add new language.
First of all i copy C:\jamify-toc\node_modules\gatsby-theme-try-ghost\src\utils\lang.js to my  C:\jamify-toc\src\gatsby-theme-try-ghost\src\utils
After that i changed some en text in my new lang.js. to test changes because en i default used lang in theme.
`const lang = {
    en: {
        MIN_READ: `Мин читать`,
        MORE_IN: `More in`,
        MORE_POSTS: `Больше постов`,
        MORE_POSTS_SM: `больше постов`,`
And yarn develop
But i don't see any changes on locaclhost
And have some warning in console - [log](http://joxi.ru/8An75bGTyR7q7r)

**Comment by styxlab** [comment]
Component shadowing would work, but it's kind of complicated for this use case.

If you send me the lang.js files with your language added, I can incorporate them in the core, so other users can benefit from it too. Note that each package has it's own lang.js that needs to be translated. Even better would be a PR that I can merge, but a plain textfile would also do.

**Comment by motherfacker** [comment]
> Component shadowing would work, but it's kind of complicated for this use case.
> 
> If you send me the lang.js files with your language added, I can incorporate them in the core, so other users can benefit from it too. Note that each package has it's own lang.js that needs to be translated. Even better would be a PR that I can merge, but a plain textfile would also do.

I have some question about translate. Example:
en: {
        MIN_READ: `min read`,

it has several translation if it would be
< 1 min read
1 min read
>2 min read
How to add this variations to lang.js?

**Comment by styxlab** [comment]
The trick here is that "min" is just an abbreviation that works both in the singular and plural case. If I had to choose the full English word "minute" than a distinction between minute and minutes would be needed.

If your language needs additional plural variants, just let me know and I try to incorporate that. But please think hard if it is really needed.

**Comment by motherfacker** [comment]
Ok, i want to try use PR do i  need to clone and change lang.js files in "gatsby-theme-try-ghost" repo or "gatsby-theme-try-ghost"?

**Comment by styxlab** [comment]
If you want to do a PR, it's best to first **make a fork**. You then clone your fork to your local machine and push your changes to the fork. You will then be able to issue a PR against the original.

**Comment by motherfacker** [comment]
which repo i should fork?

**Comment by styxlab** [comment]
[gatsby-theme-try-ghost](https://github.com/styxlab/gatsby-theme-try-ghost): that's where all development happens.

**Comment by styxlab** [comment]
@motherfacker: How is the translation going? If you have trouble making a PR, you can also send me a `lang.js` file with the translations included and I will then add them to the repo.

**Comment by motherfacker** [comment]
@styxlab The problem is the holidays. I will finish all translations this week. Thank you for reminding.

**Comment by styxlab** [comment]
Thanks so much for providing the Russian translations to the main file!

Do you have a chance to look at the other `lang.js` files in the other `packages` folder as well?

**Comment by motherfacker** [comment]
Yes, i translate all other lang.js and PR today.

**Comment by styxlab** [comment]
Will add you to the contributors list soon. Thanks so much for providing the translations!
