### ISSUE TITLE
How to display list of tags in ghost blog?

### ISSUE THREAD

**Issue by wl018** [styxlab/gatsby-theme-try-ghost#246]
I want to display all my tags in a post, how should I do?
I found [this](https://www.sitepoint.com/community/t/how-to-display-list-of-tags-in-ghost-blog/235364), but it seems like doesn't work. 

I also want to [Create A Tags List Page in Your Ghost Theme](https://medium.com/aspirethemes/how-to-create-a-tags-list-page-in-your-ghost-theme-7a151413f5b0), and the solution from **Aspire Themes** doesn't fit for this case either, how should I solve it?

Thank you for your help.

**Comment by styxlab** [comment]
The linked solutions are for original Ghost and do not apply here. The front-end code of this repo is using React. So you can fork this repo and change the front-end code directly. Better yet, use the method of component shadowing which is described in the the Jamify tutorials. In either case, you need React and coding knowledge to accomplish this task.

**Comment by styxlab** [comment]
Feel free to re-open again.
