### ISSUE TITLE
How do I create distinct layouts for Page areas

### ISSUE THREAD

**Issue by ikewabo** [styxlab/gatsby-theme-try-ghost#247]
### Is it possible to create different templates ( or layouts )  for the different menu items?

- Will like to customize the Home and landing pages (menu items pages)  in a more free format - different from the static blog style. 
- I will also like each menu page to loose the static structure by arranging content and styling it differently.

Summarily, is it possible to override your layouts with custom layouts?  Digging more into your publications, I read your suggestions to utilize Shadow Components - is it possible to blog on this topic?  That will be heavily appreciated.

THANK YOU FOR A GREAT PLUGIN!  The more I follow your blogs, the more amazing revelations - like pealing onion.  I must confess, I edited this post, after reading your post on Toc. 

THANK YOU, AGAIN!

**Comment by styxlab** [comment]
@ikewabo: Welcome to this project and thanks for the kind words.

Yes, it's entirely possible to make your own layouts, but the difficulties vary depending on the type of changes you want to make. So, let me summarize your options:

## Pages:

   1. If you just want additional "pages", you can add those in Ghost CMS and style them with the code-injection styles that you add in Ghost CMS. Every page can have its own layout.
   2. New menu items for those pages can be configured in Ghost CMS and will be automatically picked up (you can also override them the [navigation menu](https://github.com/styxlab/gatsby-starter-try-ghost#-configure) in the Gatsby config if that is really needed).

## Blog Layout

  1. You can use component shadowing as described in the Table of Contents tutorial to a) change style files and b) React code giving you full flexibility. However, I can only recommend that approach for relatively small changes. If you need an entirely different layout, you'll end up overriding a lot of components and they will likely break, once the base repo changes.
  
  2. For an entire different layout, I recommend that you fork this repo and make those changes directly in the source code. If you are able to abstract those changes so they can be packaged into a new plugin that can be installed on top of the base theme, then you can call yourself a master. This is pretty advanced, but for a lot of use cases the other options should be sufficient.

The table of contents plugin is a good example of one that adds both new functionality and changes the style. Note however, that it does not touch the general structure of the blog layout, it's more like an addition to what is already there.

**Comment by styxlab** [comment]
Close as answered. Feel free to re-open again.
