### ISSUE TITLE
Posts metatags didn't change after page load

### ISSUE THREAD

**Issue by jempurich** [styxlab/gatsby-theme-try-ghost#25]
As you can see from this post https://styxlab.github.io/welcome/

attributes in ghost e.g. title, meta attributes, etc. couldn't be add to static file

<img width="1280" alt="Screen Shot 2563-04-03 at 12 17 17" src="https://user-images.githubusercontent.com/9071940/78323793-86369880-75a5-11ea-8cfe-112ce6977ea7.png">

**Comment by styxlab** [comment]
Could you please provide some context of what you are trying to achieve and what tools you are using?

**Comment by jempurich** [comment]
> Could you please provide some context of what you are trying to achieve and what tools you are using?

The problem is when i go to posts and then meta tags didn't change.

I will compare between https://demo.ghost.io/ and https://styxlab.github.io/. please check the attachment below.
![O5TAyxNw4CT](https://user-images.githubusercontent.com/9071940/78341396-37e7c080-75ca-11ea-8095-8fdc45a11c2d.png)
![o79qX8iCjfc](https://user-images.githubusercontent.com/9071940/78341402-39b18400-75ca-11ea-9482-b19d4e50ea87.png)

**Comment by styxlab** [comment]
Thanks for providing more context and for catching this error! Yes, this will be fixed soon.

**Comment by jempurich** [comment]
@styxlab You're welcome 👍 . If you need more information please feel free to contact me

**Comment by styxlab** [comment]
This should be fixed now in the latest versions:

- [gatsby-theme-try-ghost@1.5.2](https://www.npmjs.com/package/gatsby-theme-try-ghost)
- [gatsby-starter-try-ghost@1.5.2](https://www.npmjs.com/package/gatsby-starter-try-ghost)

Please verify!

**Comment by jempurich** [comment]
Superb ! I've been upgraded and it is work.

Thank you so much for solving
