### ISSUE TITLE
what is the problem？

### ISSUE THREAD

**Issue by xiyizhou** [styxlab/gatsby-theme-try-ghost#251]
![iShot2021-02-08 19 08 07](https://user-images.githubusercontent.com/55862635/107211935-30424500-6a41-11eb-9cb3-a4151bf085d4.png)

**Comment by styxlab** [comment]
This is an ecoding issue coming from the Ghost Casper stylesheet. The relevant css is in 'screen.css' is:
```
html.casper .nav-post-title.dash:before {
    content: "– ";
    opacity: 0.5;
}
```
I think this could be solved by providing an escape sequence in the content prop. However, as I am just re-using the [original stylesheet from Ghost](https://github.com/TryGhost/Casper/blob/44fa55be19c1f1072f7ce2839939297880e65032/assets/css/screen.css#L455) this has to be solved [upstream](https://github.com/TryGhost/Casper/issues). Please open an issue on the original Ghost project first. Once they have corrected their stylesheet, it will be automatically picked up here.

**Comment by xiyizhou** [comment]
Thank you，I had fix it by change [content: "鈥� "]to [content: "– ";], but i do not know why  it happen , i download the code from https://github.com/styxlab/gatsby-theme-try-ghost

![iShot2021-02-09 09 11 32](https://user-images.githubusercontent.com/55862635/107301731-03c91000-6ab7-11eb-9a08-aea63df7ab41.png)
