### ISSUE TITLE
Extending the theme

### ISSUE THREAD

**Issue by fyodorp** [styxlab/gatsby-theme-try-ghost#254]
How hard would it be to transfer Code injection from hosted ghost blog to the JAM stack version?
I know some of it to be duplicated using the plugin's functionality, but I could not figure out how to add for example stripe checkout diving into programming.

**Comment by styxlab** [comment]
This is a Gatsby front-end so you have all the options that Gatsby provides. Integrating back-end functionality with Gatsby has always been quite hard, however, I expect Gatsby to announce new features next week and it's likely that they will add serverless capabilities. Depending on what you want to do with Stripe, you will have to solve authentication first. Unless Ghost releases an official membership API, it's not of much use here.

**Comment by styxlab** [comment]
Closing as answered. Don't hesitate to come back if you feel the question has not been fully answered.

**Comment by fyodorp** [comment]
Unrelated to this issue, but can you please msg me on Twitter @fyodorpi about your new blogging platform?
