### ISSUE TITLE
Cannot "yarn build" because it can't fetch image

### ISSUE THREAD

**Issue by Buda9** [styxlab/gatsby-theme-try-ghost#255]
Error processing images in node Ghost__Post__60390c8595395e0a87999ed4:
 url passed to createRemoteFileNode is either missing or not a proper web uri:
https://res.cloudinary.com/vokabula/images/v1585933889/Kako-se-pripremiti-za-razgovor-za-posao-na-njemačkom-besplatna-ra
dionica-vokabula/Kako-se-pripremiti-za-razgovor-za-posao-na-njemačkom-besplatna-radionica-vokabula.jpg

https://postimg.cc/gallery/z8dkVD1

So the image exists but it can't be fetched. Is there any way to "ignore" image fetching or any other way to solve this issue?

**Comment by styxlab** [comment]
That's strange as I can load the image under that address in the browser. I wonder if it has to with character encodings. Could you simplify the image name and only include English characters in them, just for a test?

If this does not help, please publish your (temporary) Ghost Content API keys, so I can analyze it further. There is no way to exclude fetching images, but you can always take them out in your Ghost CMS.

**Comment by Buda9** [comment]
Thank you for reply. I think the issue here is that it's using external image as cover image. When I reuploaded same image to ghost cms, it worked perfectly. Thank you one more time!

**Comment by styxlab** [comment]
Great that you solved the issue and thanks for reporting back!
