### ISSUE TITLE
Cannot remove 'Jamify' link in footer.

### ISSUE THREAD

**Issue by DevelopingUK** [styxlab/gatsby-theme-try-ghost#259]
I want to remove and replace the Jamify link in the footer, however, it's not disappearing after numerous failed attempts.

I have shadowed the footer by copying the 'export footer for shadowing' fix and copied index, layout and footer files into my project.

Once inside my src/components/common/ folder, I attempted to change the links inside the Footer.js file and multiple attempts have been unsuccessful.

Is it hardcoded in somewhere?

I have reverted the attempts to shadow the footer and removed index, layout and footer files while I try and work this one out.

repo: lf-new

Am I missing something really obvious here?

**Comment by styxlab** [comment]
Welcome @DevelopingUK! Component shadowing is the way to go here. Starting from the `root` directory of a `gatsby-starter-try-ghost` clone, the folder structure must be as follows:

```
src/gatsby-theme-try-ghost/
└── components
    └── common
        └── Footer.js
```

Note that there is no `src` before `components`, that's what most people find confusing. You can then modify [Footer.js](https://github.com/styxlab/gatsby-theme-try-ghost/blob/cd9d1fea4370798294c54761e652b3c48577c044/packages/gatsby-theme-try-ghost/src/components/common/Footer.js#L32) as you like to.

**Comment by DevelopingUK** [comment]
Thank you, that's exactly my problem here; I fixed it by following your instructions.
