### ISSUE TITLE
Support for Ghost v4

### ISSUE THREAD

**Issue by Kerumen** [styxlab/gatsby-theme-try-ghost#260]
Ghost v4 was [recently released](https://ghost.org/changelog/4/).

I tried to set `"version": "v4"` in my `.ghost.json` but an error was thrown:

```
Error: @tryghost/content-api Config Invalid: 'version' v4 is not supported
```

It seems that the [latest version](https://github.com/TryGhost/SDK/commit/2986ceb275b24ecdecd39b03ed38f085adb3248f) of `@tryghost/content-api` is needed to support Ghost v4. Is it possible to update the dependency version of `gatsby-source-try-ghost`?

Thanks!

**Comment by styxlab** [comment]
Thanks for reporting. I will update dependencies soon, but note that there is currently no benefit in using the 'v4' endpoint.

**Comment by Kerumen** [comment]
Yes I know, just wanted to let you know :)

**Comment by styxlab** [comment]
Closing as there is nothing to to at the moment.
