### ISSUE TITLE
Integrate Handlebar Templating

### ISSUE THREAD

**Issue by anudit** [styxlab/gatsby-theme-try-ghost#264]
Is it possible to compile Ghost's handlebar templates using Gatsby? This would mean I can directly integrate Ghost's templates like https://github.com/TryGhost/Casper and compile them using this Gatsby theme, pulling the content from a Ghost CMS using `contentApiKey`.

**Comment by anudit** [comment]
Ah I guess this isn't really possible. https://forum.ghost.org/t/gatsby-ghost-starter-adding-a-theme/16475/2

**Comment by styxlab** [comment]
This is neither possible nor desired. This repository gives you a react-frontend that fully replicates the Casper theme, effectively replacing the handlebar templates (which only work as part of the ghost core nodejs server).
