### ISSUE TITLE
Certificate Has Expired

### ISSUE THREAD

**Issue by stephencweiss** [styxlab/gatsby-theme-try-ghost#266]
Just pulled down a fresh copy of this theme from the [startes site](https://www.gatsbyjs.com/starters/styxlab/gatsby-starter-try-ghost/) and received this error when trying to build:

```shell
$ gatsby develop
 ERROR #11321  PLUGIN

"gatsby-source-try-ghost" threw an error while running the sourceNodes lifecycle:

certificate has expired
```

**Comment by styxlab** [comment]
@stephencweiss! Thanks for bringing this issue to my attention. 

Certificates have been renewed and the error should not happen again. Could you please test and confirm?

**Comment by styxlab** [comment]
Closing as solved.
