### ISSUE TITLE
hi, ive deploy it with netlify, how can i find the admin pannel?

### ISSUE THREAD

**Issue by francolamcn** [styxlab/gatsby-theme-try-ghost#268]

**Comment by styxlab** [comment]
Welcome @francolamcn! You need to deploy your own Ghost CMS instance and that's where you find your Ghost admin panel.

**Comment by francolamcn** [comment]
thanks! i just tried heroku to host ghost installation, and simply edit .ghost.json, works perfect.

**Comment by styxlab** [comment]
Glad to hear it's working now!
