### ISSUE TITLE
Site-Logo-URL is not redirecting to siteURL in case base path set to '/blog'

### ISSUE THREAD

**Issue by saurabhjain06** [styxlab/gatsby-theme-try-ghost#270]
Hi,

I am new to Gatsby and your template is good for bloggers.. 
I am just trying it out locally. 
I modified my base path url to '/blog' and used a landing page as you mentioned in your tutorial  - https://www.jamify.org/2020/04/28/routing-with-jamify/#install-the-landing-page.
Now when I navigate from landing page to blog its OK, but when I click on Site-logo to go back to landing page it is navigating to URL example.com/blog.
Any suggestion, how can I modify that other than hard coding.

**Comment by styxlab** [comment]
Hi saurabhjain06, this is how it is intended. You can configure the "Home" link to go back to your primary page.
