### ISSUE TITLE
Allow override title and description

### ISSUE THREAD

**Issue by chancharles** [styxlab/gatsby-theme-try-ghost#271]
TBH, I am running a non-standard setup where I am using Ghost as a centralized CMS for multiple blogs that are statically generated, so my use case may not be valid for this project. Anyway, I think it'd be nice to allow site title and site description (maybe even feature image) to be overridden by `siteConfig.js`. 

Today, you can already use `siteTitleMeta` and `siteDescriptionMeta` to modify the website metadata. This request is a relative small change and I can put up a PR for that if you think it's something that is useful for the project.

**Comment by styxlab** [comment]
A multi site setup would usually involve multiple Ghost CMS instances and you would then be able to set different site titles in the CMS. The aim of this repo is to support standard Ghost CMS as much as possible, but not going much beyond that. That means, as long as native Ghost does not support multiple sites within one Ghost CMS instance, I don't want to add the feature that you are proposing even if it is a relatively small change. If you really need that feature, it's better that you work with your own fork.

**Comment by chancharles** [comment]
no problem.
