### ISSUE TITLE
Allow filtering of Ghost artifacts retrieval

### ISSUE THREAD

**Issue by chancharles** [styxlab/gatsby-theme-try-ghost#272]
`gatsby-source-try-ghost` always attempts to retrieve all Ghost artifacts (posts, pages, authors, and tags). I have a use case where I want to retrieve only a *subset* of these artifacts. There is currently no such customization. 

So, I am proposing that we add a `filters` option to `gatsby-source-try-ghost` (which ultimately will be exposed through the theme's siteConfig) to let a user define a set of filters for each artifact. Here's what I have in mind:

```
{
  resolve: `gatsby-source-try-ghost`,
  options: {
...
    filters: {
      posts: (post) => ...,
      pages: (page) => ...,
      authors: (author) => ...,
      tags: (tag) => ...,
    }
  },
},
```

All filters are optional and will not filter anything by default.

**Comment by styxlab** [comment]
Hi @chancharles! I support a filter approach for posts and pages. As there are inherent relations from posts to authors and tags, I would not want to allow filtering those, because you could run into errors with this configuration. So, if you want to make a PR for posts and pages, you can go ahead.

**Comment by chancharles** [comment]
PR created https://github.com/styxlab/gatsby-theme-try-ghost/pull/273
