### ISSUE TITLE
Not able to find gatsby-rehype-remote-images plugin

### ISSUE THREAD

**Issue by saurabhjain06** [styxlab/gatsby-theme-try-ghost#276]
My ghost installation is local and I want to import all my post images during Gatsby build.
I searched some closed issues and found that it can be achieved via gatsby-rehype-remote-images plugin.
But, I couldn't find this plugin..
Can you please help how to import my post images.
Thanks

**Comment by styxlab** [comment]
https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free/#add-plugin-for-inline-images

**Comment by saurabhjain06** [comment]
You are really cool..
