### ISSUE TITLE
Some images has processed srcset but only renders the placeholder

### ISSUE THREAD

**Issue by lacsinagramar** [styxlab/gatsby-theme-try-ghost#280]
I have blog posts on ghost, all has `feature_image` but some of the featured image aren't rendered.

![image](https://user-images.githubusercontent.com/29629828/130732624-6ba90045-77fb-4486-ae86-60e8d8682cd5.png)

Seems like the files processed aren't existing because when I hover my cursor to the image link in the inspect element there is no popover showing up.

**Comment by sawilde** [comment]
^ I am seeing similar to the above but only when I am developing locally (ie `yarn develop`) when I publish via netlify and create the static site all is good.

**Comment by lacsinagramar** [comment]
@sawilde Thanks, it does work when built on netlify.

**Comment by styxlab** [comment]
It could be due to network interruptions during the build process which are less likely when images are fetched from a provider with gigabit connections. Another reason I can think of is rate limiting that you can control in the config of your Ghost CMS.
