### ISSUE TITLE
Headline tags in content page not showing properly

### ISSUE THREAD

**Issue by jempurich** [styxlab/gatsby-theme-try-ghost#29]
Hi styxlab,

I found a little bug from dark mode plugin.

As you can see in content page there is some css not showing properly. When the dark mode is disable i couldn't be able to see headline in content page.

<img width="1280" alt="Screen Shot 2563-04-07 at 12 19 58" src="https://user-images.githubusercontent.com/9071940/78630004-2ef93680-78cb-11ea-9443-f93c47a4b042.png">

**Comment by styxlab** [comment]
I can confirm that this is bug of the the dark mode plugin [gatsby-theme-dark-mode](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-dark-mode). Will try to fix this.

**Comment by styxlab** [comment]
Solved in:

- [gatsby-theme-ghost-dark-mode@1.0.6](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-dark-mode)

and updated related packages accordingly:

- [gatsby-theme-try-ghost@1.6.2](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-try-ghost)
- [gatsby-starter-try-ghost@1.6.2](https://github.com/styxlab/gatsby-starter-try-ghost)

Demo was updated as well. Thanks for catching this bug!

**Comment by jempurich** [comment]
Thanks for solving !!
