### ISSUE TITLE
Errors on Development process

### ISSUE THREAD

**Issue by LeonardoGentile** [styxlab/gatsby-theme-try-ghost#297]
Hello, 
I've just launched the dev process for the first time to try out the theme.
I can't get it to work, sometimes I get multiple timeout errors and the last one closes the socket and the whole process fails:

```
 ERROR 

Error processing images in node Ghost__Post__618976fefc849516e6c903d9:
 failed to process https://d29wtipmfucw8r.cloudfront.net/2021/11/DSC_0160.JPG
TimeoutError: Timeout awaiting 'send' for 30000ms

 ERROR 

socket hang up
```

Although I can access these pictures from my browser so they do exist.

Sometimes I get this different error if I launch the develop script from vscode:

```
Generating development JavaScript bundle failed

Can't resolve 'url' in '/Users/myuser/Dev/try-ghost-gatsby/node_modules/gatsby-theme-try-ghost/src/components/common/meta'

If you're trying to use a package make sure that 'url' is installed. If you're trying to use a local file make sure that the path is correct.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
        - install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "url": false }

File: node_modules/gatsby-theme-try-ghost/src/components/common/meta/ArticleMeta.js:10:0
```

- gatsby@3.14.6
- node v16.4.1
- npm 7.18.1

**Comment by styxlab** [comment]
As announced in the README, I do not actively support this repo anymore. However, if you find a bug and a solution, I am more than happy to merge new PRs.

If you are looking for an alternative with proper support, I can recommend [next-cms-ghost](https://github.com/styxlab/next-cms-ghost). It's the successor of this project.
