### ISSUE TITLE
failed Building static HTML for pages

### ISSUE THREAD

**Issue by jempurich** [styxlab/gatsby-theme-try-ghost#35]
Can not build the site when i was using my own ghost content API (.ghost.json)

https://github.com/jempurich/gatsby-starter-try-ghost/commit/1452214d0e55147c9a5db53074d1320d9e2f92e6

Please check my deploy log below.
<img width="1160" alt="Screen Shot 2563-04-10 at 19 01 29" src="https://user-images.githubusercontent.com/9071940/78986433-d1304d00-7b5d-11ea-8017-1f57e0c6d41e.png">

error Building static HTML failed for path "/init/"
6:37:53 PM:   10 | const PreviewPosts = ({ posts, primaryTagCount, prev, next }) => {
6:37:53 PM:   11 |     const primaryTag = posts && posts[0] && posts[0].node && posts[0].node.primary_tag
6:37:53 PM: > 12 |     const url = routing(primaryTag.url, primaryTag.slug)
6:37:53 PM:      |                                    ^
6:37:53 PM:   13 |
6:37:53 PM:   14 |     return (
6:37:53 PM:   15 |         <aside className="read-next outer">
6:37:53 PM: 
6:37:53 PM:   WebpackError: TypeError: Cannot read property 'url' of undefined
6:37:53 PM:   
6:37:53 PM:   - PreviewPosts.js:12 PreviewPosts6:37:53 PM:     node_modules/gatsby-theme-try-ghost/src/components/common/PreviewPosts.js:12    :36

**Comment by styxlab** [comment]
Looks like your post is missing a tag (every post should have at least one).

In any case, build should not fail - I’m going to put in some more safeguards.

**Comment by jempurich** [comment]
> Looks like your post is missing a tag (every post should have at least one).
> 
> In any case, build should not fail - I’m going to put in some more safeguards.

In my case every post have tag but still can't build static file.

Feel free to ask me for further information :)

**Comment by styxlab** [comment]
Could you please publish your contentAPI keys, so I can try to reproduce the issue internally?

**Comment by jempurich** [comment]
> Could you please publish your contentAPI keys, so I can try to reproduce the issue internally?

Content API Key : 1e36699cfc57f6a62d68b7aa9b
API URL : https://webmeupdigital.com

--

**Comment by styxlab** [comment]
Thanks for the keys. I was able to reproduce the issue. Turns out to be an unwanted side effect of the advanced routing feature. Preview uses other posts with the same tag, but if there are no other posts for that tag, preview is empty. The new code for routing was not prepared for empty previews, hence this error.

I have fixed the issue in the latest version 1.7.4. Please check.
