### ISSUE TITLE
Detecting Routing from Ghost (node.url)

### ISSUE THREAD

**Issue by danielclough** [styxlab/gatsby-theme-try-ghost#38]
I see that you have implemented a routing solution. :clap: 

It seems that I have to change the routing in Ghost and the theme will adapt.

I found this article, and wanted to get some advice before I dig in.
https://ghost.org/docs/api/v3/handlebars-themes/routing/redirects/

Should I be making a redirect from `/` to `/blog`?
Or, doing something in the the routing file or the redirect file?

Do you have an example use case I can look at?

**Comment by danielclough** [comment]
It seems that will add a prefix on every folder?
Will `createPage` route to, for example, `website.com/blog/page/articleName`?

---

If I change this in the node-modules folder it works to change the the theme `pageNumber 0` to `/blog` but when I shadow the file to `/src/gatsby-theme-try-ghost/gatsby-node.js` - it doesn't work - I don't understand why?

``` 
    paginate({
        createPage,
        items: posts,
        itemsPerPage: postsPerPage,
        component: indexTemplate,
        pathPrefix: ({ pageNumber }) => {
            if (pageNumber === 0) {
                return `/blog`
            } else {
                return `/page`
            }
        },
    }) 
```

**Comment by styxlab** [comment]
Configure `routes.yaml` on headless Ghost, and test that routes are working as expected there. Relevant docs for configuring routes in Ghost are:

- [Custom Routes](https://ghost.org/docs/api/v3/handlebars-themes/routing/routes/)
- [Dynamic Routing](https://ghost.org/tutorials/dynamic-routing/)

The new routing feature of this repo will adapt to exactly what has been configured on Ghost. For example, if you move your blog from `/` to `/blog` with changing `routes.yaml`, this will be replicated here with zero configuration.

**Comment by styxlab** [comment]
Closing as answered.
