### ISSUE TITLE
Include BasePath as option?

### ISSUE THREAD

**Issue by aesmonty** [styxlab/gatsby-theme-try-ghost#42]
Is it possible to provide the `basePath` to this theme, in a similar way to the official Gatsby Blog Theme?
Ex:
```
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-theme-blog`,
      options: {
        // basePath defaults to `/`
        basePath: `/blog`,
      },
    },
  ],
}
```
Thank you for your time,
Andrés

**Comment by styxlab** [comment]
Currently, this repo does not provide a `basePath` option. I think you could use the `--prefix-path` command line option when calling the `gatsby` cli commad, but I have not tested this.

The recommended way of changing the base path is to change routes on the Ghost side. Ghost has a `routes.yml` file where you can highly customize your routes (not just the base path). See their documentation on configuring [custom routes](https://ghost.org/docs/api/v3/handlebars-themes/routing/routes/). 

With the advanced routing feature that was added recently, all changes to routes will be replicated when sourcing in the content from headless Ghost CMS.

In addition to these options, you may want to change routes on your reverse proxy (e.g. nginx) instead as this is also a highly flexible solution.

So, the `basePath` option would be a nice to have, but so far I am missing a stronger argument why it is needed.

**Comment by aesmonty** [comment]
Thanks for the answer.

The `--prefix-paht` option is not suitable, because my goal is to have a custom Gatsby landing page at `/`, and all the blog-related stuff coming from this theme prefixed by `/blog`.

It seems the dynamic routing approach is more suited when using the Ghost built-in frontend, not when using Ghost as a headless CMS. So far, I have not been able to get it to work. I'll let you know if I get to fix it.

https://forum.ghost.org/t/ghost-on-the-jamstack/4925/8

**Comment by styxlab** [comment]
The dynamic routing approach with changing routes in `routes.yml` is working (note that the forum posts refers to another repo!).

However, I realize that messing with `routes.yml` seems overly complicated for your use case. I will therefore implement the `basePath` option and integrate it in the next release.

**Comment by danielclough** [comment]
Thank you!

**Comment by aesmonty** [comment]
Thank you, @styxlab !

Could you please share with me here your working version of the `routes.yml` file?

**Comment by styxlab** [comment]
Please try to get it working with Ghost first (and use their forum, if you get stuck). I think this can be done with collections in routes.yaml (also see their [tutorial](https://ghost.org/tutorials/custom-home-page/)):

```text
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
```

**Comment by styxlab** [comment]
The `basePath` option is now available for `versions >= 1.9.0` 🎉

**Comment by aesmonty** [comment]
That was fast @styxlab ! Thank you so much. Feel free to open tickets and issues, I may be able to collaborate in the future :)

**Comment by styxlab** [comment]
@aesmonty: Am looking forward to your contributions!

**Comment by aesmonty** [comment]
Do you have any roadmap of features you are planning to implement? 
The newsletter feature is missing at the moment, but have you identified other possible improvements?

**Comment by styxlab** [comment]
Yes, a good starting point is [here](https://github.com/styxlab/gatsby-theme-try-ghost/blob/master/CONTRIBUTING.md). Google AMP pages is also high up on my wishlist.
