### ISSUE TITLE
Page Not Found Error (404) on "tag" and "author" tabs

### ISSUE THREAD

**Issue by techandsec** [styxlab/gatsby-theme-try-ghost#43]
After removing all of the "ghost" user default post I get a Page Not Found Error (404) on the "tag" and "author" tabs.

The links dont seem to have updated as the links still point to the follow:

[domain]/tag/getting-started/
[domain]/author/ghost/

<img width="408" alt="Screen Shot 2020-04-21 at 13 23 41" src="https://user-images.githubusercontent.com/61643810/79894383-5d9b0500-83d3-11ea-99e5-5bd4dab83891.png">

**Comment by styxlab** [comment]
If you remove the user, then there is no author "ghost" anymore. So I would expect that you get a 404 on those endpoints.

The menu items "Tags" and "Authors" that you find in the top navigation bar are manually configured in the Ghost Sdmin interface, so you have to change things there. I bet you get exactly the same error when you click on those menu items in the preview shown within Ghost Admin, so this is how it should be.

**Comment by techandsec** [comment]
You are right. I corrected the issue in the portal. Thanks
