### ISSUE TITLE
Copy To Clipboard on Code Snippet

### ISSUE THREAD

**Issue by techandsec** [styxlab/gatsby-theme-try-ghost#44]
Is it possible to add a copy function/button to code snippets to make it easier for readers to copy the data in the code block?

<img width="773" alt="Screen Shot 2020-04-21 at 13 19 46" src="https://user-images.githubusercontent.com/61643810/79894000-d51c6480-83d2-11ea-849f-943a346b5d0d.png">

**Comment by styxlab** [comment]
This would definitely be great enhancement to [gatsby-rehype-prismjs](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-rehype-prismjs).

Do you think you could contribute that feature with a little help from my end?

**Comment by styxlab** [comment]
Set this on the feature list. This is low priority, but will be handled on next `rehype-prismjs` rennovation.
