### ISSUE TITLE
Pass `tableOfContents` to rehype-plugins

### ISSUE THREAD

**Issue by Kerumen** [styxlab/gatsby-theme-try-ghost#45]
First of all, thanks for your repo, it provides awesome resources to hack Ghost and to make it better. I love it!

I try to implement a custom `tableOfContents` for my posts but _within_ the blog post. Hence, I wanted to replace a custom div with my toc markup:

```
<div id="toc"></div> -> <ul><li>Heading 1</li>...</ul>
```

I tried to write a `gatsby-rehype-*` plugin to visit my post html and replace my target div with my markup. However, I was surprised `tableOfContents` is not passed to plugins and only provided for the "end-user", Gatsby.

Do you think it's possible to make that field available to rehype-plugins?

If not, do you have a suggestion for my problem? I've seen the `TableOfContents` component shadowing in your example, but that's not what I want because the TOC would be outside of the article.

Thanks!

**Comment by styxlab** [comment]
Thanks a lot for your positive feedback :smile: 

Maybe the existing [gatsby-theme-ghost-toc](https://github.com/styxlab/gatsby-theme-try-ghost/tree/master/packages/gatsby-theme-ghost-toc) plugin is all you need as it shows the toc only outside articles on wide screens. On mobiles and smaller screen sizes it automatically moves the content from the side to the top of the article (below the feature image).

To your original question: the `toc` data structure should be made available to all `gatsby-rehype-*` plugins, I simply forgot to pass it through. If you want to fix that, you are more than welcome to issue a PR!

**Comment by Kerumen** [comment]
I could try a PR but I'm sur the direction to take. Currently the `tableOfContents` is computed only one time, [at the end of the file](https://github.com/styxlab/gatsby-theme-try-ghost/blob/5fd4eb9ee9c80f5559dff34ee59774ff26de3400/packages/gatsby-transformer-rehype/src/extend-node-type.js#L232) when we resolve everything. Do you think it makes sense to compute it at the beginning, before calling the plugins?

Also I don't understand [this chunk](https://github.com/styxlab/gatsby-theme-try-ghost/blob/5fd4eb9ee9c80f5559dff34ee59774ff26de3400/packages/gatsby-transformer-rehype/src/extend-node-type.js#L77-L89) vs [this chunk](https://github.com/styxlab/gatsby-theme-try-ghost/blob/5fd4eb9ee9c80f5559dff34ee59774ff26de3400/packages/gatsby-transformer-rehype/src/extend-node-type.js#L92-L105). They look very similar and I don't get the difference.

**Comment by styxlab** [comment]
This is a bit tricky as getTableOfContents() is an async function. You don't need to move the function to another place. 

Rather then trying to execute the function, I would pass the function promise to all plugins, so it can be resolved within the plugin. Only the second chunk is relevant here ([see this discussion](https://github.com/gatsbyjs/gatsby/issues/23409) on why you may want to keep the first chunk in as well). With tableOfContents added it could look similar to:

```javascript
// in gatsby-transformer-rehype, extend-node-type.js
const htmlAst = rehype.parse(htmlNode.internal.content)
const tableOfContents = getTableOfContents(htmlNode)

await Promise.each(pluginOptions.plugins, (plugin) => {
    const requiredPlugin = require(plugin.resolve)
    // Allow both exports = function(), and exports.default = function()
    const defaultFunction = _.isFunction(requiredPlugin)
        ? requiredPlugin
        : _.isFunction(requiredPlugin.default) ? requiredPlugin.default : undefined
    if (defaultFunction) {

        return defaultFunction({ htmlAst, tableOfContents, htmlNode, getNode, basePath,
            reporter, cache: getCache(plugin.name), getCache,
            compiler: { parseString: rehype.parse.bind(rehype), generateHTML: null },
            ...rest }, plugin.pluginOptions)
    } else {
        return Promise.resolve()
    }
})
```


Then, in your rehype plugin, you can use this as follows:

```javascript
module.exports = ({ htmlAst, tableOfContents, htmlNode, reporter }, themeOptions) => {
    tableOfContents.then(toc => console.log(toc))
```
Hope this makes sense.

**Comment by Kerumen** [comment]
Okay, I'll try to propose a PR soon. Thanks!

**Comment by styxlab** [comment]
@Kerumen: Could you please [get in contact](https://atmolabs.org/contact/) with me? Thanks!
