### ISSUE TITLE
Issue with the starter

### ISSUE THREAD

**Issue by stephenajulu** [styxlab/gatsby-theme-try-ghost#48]
Hi, how are you?
I am using your starter. I did everything right until the adding api keys step.
I didn't find the .ghost.json file and according to the starter(or to me) i am supposed to define the apis in siteconfig. Could you kindly help me by showing me how and where to put the apis. Is there something i should add to the siteconfig or to the main gatsby-config file?
`try {
    ghostConfig = require(`./.ghost`)
} catch (e) {
    ghostConfig = {
        development: {
            apiUrl: process.env.GHOST_API_URL,
            contentApiKey: process.env.GHOST_CONTENT_API_KEY,
        },
        production: {
            apiUrl: process.env.GHOST_API_URL,
            contentApiKey: process.env.GHOST_CONTENT_API_KEY,
        },
    }
} finally {
    const { apiUrl, contentApiKey } = process.env.NODE_ENV === `development` ? ghostConfig.development : ghostConfig.production
    if (!apiUrl || !contentApiKey || contentApiKey.match(/<key>/)) {
        ghostConfig = null //allow default config to take over
    }
}`

here's both my site config and gatsby config

[athcms gatsby config file](https://github.com/stephenajulu/athcmsbeta/blob/master/gatsby-config.js)
[athcms site config file](https://github.com/stephenajulu/athcmsbeta/blob/master/siteConfig.js)

**Comment by danielclough** [comment]
Put .ghost.json in your root directory.

{
  "development": {
    "apiUrl": "https://address.tld",
    "contentApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "production": {
    "apiUrl": "https://address.tld",
    "contentApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}

**Comment by stephenajulu** [comment]
Thank you

**Comment by stephenajulu** [comment]
Hi i added the .ghost.json but my content still hasn't updated to the content on my ghost install on heroku. It still shows the old posts. What should i do?

**Comment by styxlab** [comment]
The answer from @danielclough is correct.

Please make sure your file is named `.ghost.json` (two dots!) and that it is placed in the root directory of your starter. Also look into any errors during the build process.

If it still doesn't work, please publish the content of your `.ghost.json` here, then I can use my tools to debug further.

**Comment by stephenajulu** [comment]
It works thank you.
