### ISSUE TITLE
Post count on author pages stays under 3

### ISSUE THREAD

**Issue by tobimori** [styxlab/gatsby-theme-try-ghost#54]
The demo [here](https://styxlab.github.io/author/ghost/) says 3 even though the Ghost user has 7 posts.

**Comment by styxlab** [comment]
Bug confirmed. Maybe you want to fix this, too? Let me know.

**Comment by tobimori** [comment]
Should be fixed with #55 but haven't tested it yet 👀

**Comment by styxlab** [comment]
Perfect. Thanks!
