### ISSUE TITLE
Props are not updated when navigating internal links

### ISSUE THREAD

**Issue by LukasJokubas** [styxlab/gatsby-theme-try-ghost#57]
Hi,

Out of the box just installing gatsby-theme-try-ghost starter and connecting to my Ghost instance, I noticed that clicking through the main navigation of the site pointing to /tag/ links, updates the collection title and posts count displayed on the page, but posts are not updated. Hitting F5 and fully refreshing the collection page seems to work and correct posts are then displayed.

I think it might be related to gatsby-plugin-catch-links plugin, however bellow snippet in gastby-config.js doesn't seem to help.

```
{
      resolve: `gatsby-plugin-catch-links`,
      options: {
        excludePattern: /(tag)/,
      },
},
```

Could you please help to resolve this?

**Comment by styxlab** [comment]
This is probably related to issue #53. Could you please set `postsPerPage` to a large number (e.g. 100) in `siteConfig.js` and see if the problem vanishes?

**Comment by styxlab** [comment]
Closing in favour of #53.
