### ISSUE TITLE
How to pull content from ourself not from ghost content api key

### ISSUE THREAD

**Issue by KontenaIndonesia** [styxlab/gatsby-theme-try-ghost#6]
Hi there,
Can I pull content not from ghost api key? Looks like this official repo https://github.com/TryGhost/gatsby-starter-ghost

Or if can do it, let me know the guideline DIY

**Comment by styxlab** [comment]
@KontenaIndonesia: Could you please get in [contact](https://atmolabs.org/contact) with me? I'd like to understand how you set up a TOC with ghost Heroku.
