### ISSUE TITLE
deprecated warnings during install

### ISSUE THREAD

**Issue by umsaenga** [styxlab/gatsby-theme-try-ghost#62]
Hello - trying to install and use ghost theme.  During install I received errors relating to being deprecated.

> npm WARN deprecated core-js@2.6.11:  [...]
> npm WARN deprecated request@2.88.2:  [...]
> npm WARN deprecated @babel/polyfill@7.8.7:  [...]
> npm WARN deprecated chokidar@2.1.8:  [...]
> npm WARN deprecated fsevents@1.2.13:  [...]
> npm WARN deprecated resolve-url@0.2.1:  [...]
> npm WARN deprecated urix@0.1.0:  [...]

Later when I try to develop I get several more warnings and errors (attached) and not being able to develop. 

Are the deprecated warning issues causing the later ones?  I tried to search around and couldn't find many answers. 

Thank you

> 
[ghostErrorsFull.txt](https://github.com/styxlab/gatsby-theme-try-ghost/files/4633388/ghostErrorsFull.txt)

>  ERROR #98123  WEBPACK  [...]
>  warn There are multiple modules with names that only differ in casing. [...]
the full output is attached.

**Comment by umsaenga** [comment]
Forgot to mention that I did look through this thread https://github.com/styxlab/gatsby-theme-try-ghost/issues/10.  and still received error

**Comment by styxlab** [comment]
These are all very strange errors. I don't have a solution, but some pointers, that may help you:

1. Before using `gatsby-theme-try-ghost` you should start with `gatsby-starter-try-ghost` and see if you can get it compiled. The starter s a user version whereas the theme is for developers.

2. Make sure you start from a fresh clone. I see some very strange message indicating that you are not running the latest version or made modifications to the code yourself.

3. I see that you directly use `gatsby develop`, but you should use `yarn develop` as the theme is setup as a monorepo with workspaces that are only correctly handled with `yarn`.

4. Before using `yarn develop`, make sure use issue `yarn`, so all packages are updated correctly. Do not mix `npm` and `yarn`, only use `yarn` with this repo.

5. Looks like you are using windows OS which is not supported. Try using it on linux if you can.

6. Especially the webpack failures are indicating a general problem with your OS/gatsby/react setup.

Let me know, if you get it to work. I keep my fingers crossed!

**Comment by umsaenga** [comment]
1. I thought I did use starter try ghost. tried again with same deprecated warnings

2. it is fresh clone, have not made any mods.

3. tried yarn on my existing and seems to work now. 

5. should I avoid this starter then? will i run into more problems with windows?

6. odd, all other works fine.

Thank you for prompt reply

**Comment by styxlab** [comment]
Okay, if you used the starter just stick with it unless you want to make improvements to the code base, I was just guessing. This should work on windows, but I cannot give support for this OS as I have no means of testing it there. So, you have a working version on your second clone?

**Comment by umsaenga** [comment]
> So, you have a working version on your second clone?
it tends to be inconsistent, sometimes it works, sometimes no.  

Also try to `yarn build` and doesn't 

Thank you

[ghostBuildErrors.txt](https://github.com/styxlab/gatsby-theme-try-ghost/files/4634571/ghostBuildErrors.txt)

**Comment by styxlab** [comment]
This is really strange, and I cannot help you further with this. I propose that you publish your exact development stack and OS version here, maybe someone else who is also using windows can help you with this. I'll keep this issue open a couple of days. Please also report if you find out the issue yourself.

**Comment by umsaenga** [comment]
> As described in the Gatsby on Windows docs

I will try this today and report back.  thank you!

**Comment by umsaenga** [comment]
I have tried this with no success.
Also tried several other starter themes and they seem to work fine.  Thank you, for trying to help.

**Comment by styxlab** [comment]
Thanks for reporting back. Could you please tell us your exact development stack, so we can try to reproduce this ourselves?

**Comment by umsaenga** [comment]
sorry, new to this, how do I do this?

**Comment by styxlab** [comment]
Please publish your exact install instructions as outlined in #63.
