### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by styxlab** [styxlab/gatsby-theme-try-ghost#63]
It was reported on #62 that installing this repository on windows did not work.

According to the Gatsby docs, it should be possible to run this project by using the Windows Subsystem for Linux (WSL).

Opened this issue to test / update this project so it runs on WSL without problems.

**Comment by tobimori** [comment]
I worked on this theme on Windows and it went fine (for me).

**Comment by styxlab** [comment]
_For me, the starter is also working._
Here are my test results on **Windows 10, Version 1909 (Build 18363.836)**, based on
- [WSL 1](https://docs.microsoft.com/de-de/windows/wsl/install-win10)
- Ubuntu 18.04. LTS
- Installation following these [Gatsby docs](https://www.gatsbyjs.org/docs/gatsby-on-linux/#windows-subsystem-linux-wsl)
- Making sure to install node version `12`
```bash
node -v
v12.16.3
```
- Gatsby is installed with:
```bash
npm -g install gatsby
```
The starter is installed exactly as described in the [README](https://github.com/styxlab/gatsby-starter-try-ghost):
```bash
gatsby new try-ghost https://github.com/styxlab/gatsby-starter-try-ghost
cd try-ghost
gatsby develop
```
After compile, I was then able to see the demo site on `http://localhost:8000`.
Note: Windows asked me for permissions to start the http server which I had to explicitly allow.

```bash
[try-ghost]$ gatsby -v
Gatsby CLI version: 2.12.21
Gatsby version: 2.21.1
```
**For anyone having trouble using this project with Windows:** _Please test with the outlined install instructions, before submitting an issue. If you still have problems, please post your install instructions together with the exact version numbers in the same format as shown above._
