### ISSUE TITLE
Commento server links provided through gatsby-theme-ghost-commento are lost after page reload

### ISSUE THREAD

**Issue by Prinz** [styxlab/gatsby-theme-try-ghost#66]
Hey there, thank you very much for all the work you've done so far for this theme as well as the array of accompanying plugins, they're really well made. I've started a blog using `gatsby-starter-try-ghost` as the base, and enabled both `gatsby-rehype-ghost-links` (enabled by default from the starter) and `gatsby-theme-ghost-commento`. I think there's a bug where any links in a page referencing the provided Commento server to `gatsby-theme-ghost-commento` gets rewritten to start from `/`, i.e. absolute links that are not exactly of the static site's host gets rewritten to be relative. 

Here's a reproduction GIF:
![bug](https://user-images.githubusercontent.com/32435499/82161829-13a12400-9898-11ea-8d6d-a838a9dda358.gif)

As you can see, when I start from my home page and click on a post, the Commento link is untouched and works. However, if you were to refresh directly from a page, that link (for commento.js) gets rewritten. I'm thinking this is possibly because my Commento server contains the same string as my static site, i.e. `commento.monobytes.com` contains the host of my static site server `monobytes.com`.

**Comment by styxlab** [comment]
Thanks for reporting this issue. Could you please verify that plugin `gatsby-rehype-ghost-links` is making the trouble by de-installing it? Just to be absolutely sure.

**Comment by Prinz** [comment]
I've commented out `resolve: 'gatsby-rehype-ghost-links',` and strangely enough the request for Commento still gets rewritten to be relative when refreshing a page.
My plugins in order are
* gatsby-theme-try-ghost
* gatsby-theme-ghost-dark-mode
* gatsby-theme-ghost-commento
* gatsby-transformer-rehype
  * gatsby-rehype-ghost-links (now commented out)
  * gatsby-rehype-prismjs

I've done no other changes to the codebase apart from using the plugins.

**Comment by styxlab** [comment]
It makes sense, because if `gatsby-rehype-ghost-links` would be rewriting the `url`, then you would have a relative `url` already on initial page load.

The problem is that the `ThemeProvider` `url` is emptied on page reloads. I have to think about how to solve this. One way could be to inject the `url` on a global level, but maybe there are better alternatives.

**Comment by styxlab** [comment]
@Prinz: Please verify!

**Comment by styxlab** [comment]
@Prinz: Please verify!

**Comment by Prinz** [comment]
Updated `gatsby-theme-ghost-commento` to 1.1.2 and sure enough, it got fixed, and really quick too. Thanks @styxlab
