### ISSUE TITLE
gatsby-theme-ghost-dark-mode: when dark mode is enabled, user's preference for light mode isn't respected on page refresh

### ISSUE THREAD

**Issue by Prinz** [styxlab/gatsby-theme-try-ghost#68]
One more small bug if you don't mind, probably in the same vein!

Reproduction:
1. Set defaultModeDark to true in gatsbyConfig
2. View site and change to light mode
3. Refresh
4. Observe that site reverts to dark mode

**Comment by styxlab** [comment]
Mmm, isn't that the way it should be? If you set `defaultModeDark=true` it should always show dark mode on _initial_ load. Why would you want to make the _reload_ different from the _initial_ load?

**Comment by styxlab** [comment]
Given the explanation that I wrote for that option:
```
// Set to true if you want your theme to default to dark mode (default: false)
// Note that this setting has an effect only, if
//    1. The user has not changed the dark mode
//    2. Dark mode is not reported from OS
defaultModeDark: false,
```
I now think that the user choice should always take precedence over this setting.
So a _reload_  is indeed different from a _initial_ load, if user has changed the mode in between.

Fix is coming soon.
