### ISSUE TITLE
Netifly build failed  Error: connect ECONNREFUSED 127.0.0.1:2368

### ISSUE THREAD

**Issue by pavlenex** [styxlab/gatsby-theme-try-ghost#72]
Hey, great tool, however I'm having troubles with building it on Netifly.
1. Created a local ghost instance
2. Did this `npx npm gatsby new try-ghost https://github.com/styxlab/gatsby-starter-try-ghost`
3. Created .ghost json and configured it
4.  Created new GitHub repo [here](https://github.com/pavlenex/blog)
5.  Git pushed 
6. Connected to Netifly and tried to build, but got the error log below.

```
5:08:56 PM: success onPreInit - 0.012s
5:08:56 PM: success delete html and css files from previous builds - 0.021s
5:08:56 PM: success initialize cache - 0.007s
5:08:56 PM: success copy gatsby files - 0.054s
5:08:56 PM: success onPreBootstrap - 0.008s
5:08:56 PM: success createSchemaCustomization - 0.031s
5:08:56 PM: info GhostPost/feature_image/data-schema/https://images.unsplash.com/photo-1532630571098-79a3d222b00d?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ&s=a88235003c40468403f936719134519d
5:08:56 PM: info GhostPage/feature_image/data-schema-page/https://images.unsplash.com/photo-1532630571098-79a3d222b00d?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ&s=a88235003c40468403f936719134519d
5:08:56 PM: error "gatsby-source-ghost" threw an error while running the sourceNodes lifecycle:
5:08:56 PM: connect ECONNREFUSED 127.0.0.1:2368
5:08:56 PM: 
5:08:56 PM:   Error: connect ECONNREFUSED 127.0.0.1:2368
5:08:56 PM: 
5:08:56 PM: not finished source and transform nodes - 0.142s
5:08:56 PM: Skipping functions preparation step: no functions directory set
5:08:56 PM: Caching artifacts
5:08:56 PM: Started saving node modules
5:08:56 PM: Finished saving node modules
5:08:56 PM: Started saving build plugins
5:08:56 PM: Finished saving build plugins
5:08:56 PM: Started saving yarn cache
5:08:56 PM: Finished saving yarn cache
5:08:56 PM: Started saving pip cache
5:09:03 PM: Finished saving pip cache
5:09:03 PM: Started saving emacs cask dependencies
5:09:03 PM: Finished saving emacs cask dependencies
5:09:03 PM: Started saving maven dependencies
5:09:03 PM: Finished saving maven dependencies
5:09:03 PM: Started saving boot dependencies
5:09:03 PM: Finished saving boot dependencies
5:09:03 PM: Started saving go dependencies
5:09:03 PM: Finished saving go dependencies
5:09:06 PM: Error running command: Build script returned non-zero exit code: 1
5:09:06 PM: Failing build: Failed to build site
5:09:06 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
5:09:06 PM: Finished processing build request in 1m11.637727655s
```

Any idea of what I'm doing wrong? 

My config is available [here](https://github.com/pavlenex/blog).

Thanks.

**Comment by tobimori** [comment]
Netlify can't access a local Ghost instance hosted on your pc.

**Comment by tobimori** [comment]
This is just for triggering a new build when you change content on your Ghost site, not delivering content. You need to make your Ghost available to the outer world if you want to use it as a backend for Gatsby. Also, localhost defaults to your current computer, not exactly your computer.

**Comment by pavlenex** [comment]
Thanks.

Is that the reason why these [instructions](https://github.com/styxlab/gatsby-starter-try-ghost#ghost-content-api-keys) are missing from the repo readme ?

I am also following this [tutorial](https://josebrowne.com/tutorial-static-blog-using-headless-ghost-2-0-gatsby-netlify/) and basically replacing  `gatsby-starter-ghost` with `styxlab/gatsby-starter-try-ghost` 

I actually manage to get the website deployed earlier today with this, but getting the error mentioned on my second attempt.

**Comment by pavlenex** [comment]
Oh my, I am blind `gatsby-theme-try-ghost` and `
`gatsby-starter-try-ghost ` aren't the same. So I am having issue with `gatsby-starter-try-ghost` 🤦

**Comment by tobimori** [comment]
You can't got your site deployed like this because Netlify can never get the content. Please follow the Readme of [styxlab/gatsby-starter-try-ghost](https://github.com/styxlab/gatsby-starter-try-ghost).

**Comment by pavlenex** [comment]
Any idea why the issues aren't enabled there? Yup, I mixed things up, trying again and will report back. Thanks for quick replies.

**Comment by tobimori** [comment]
Because that repository is just a starter repo with preconfigured plugins that are hosted in this repo. You're fine with staying here with your issue, but it's still a configuration issue from your site. Netlify can't access your Ghost instance because you defined a local instance in `.ghost.json `. Netlify needs to be able to source from your instance and will always link back to your instance for inline images - so you need a server to run Ghost on.

**Comment by pavlenex** [comment]
@tobimori Thanks. I may give up then. My goal is having ghost locally, editing posts,etc then publishing on GitHub Pages/Netifly and having it as a static site on a custom domain.

It was an interesting learning curve, as this is all new to me.

**Comment by tobimori** [comment]
Using Gatsby with Ghost on a local machine is sadly not possible because of the way Gatsby (and this repository) handles Ghosts In-Post-Images. 

You should be able to use the linked repository with a custom domain by adding a `CNAME` file with the desired domain name to your GitHub repository, pointing your Domain records to GitHub's server as described [here](https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site) and enabling GitHub Pages. You could also select that repository (so where the script uploaded the static files) to deploy to Netlify. The build process happens on your computer and the script will upload correctly to GitHub, so there won't be problems like with Gatsby. Unfortunately, I can't give support you with that.

**Comment by pavlenex** [comment]
Thanks for clarification, I'll re-direct my research in that direction. Glad I discovered Gatsby and this repo nevertheless may come in handy for the future projects. Thanks for your help, appreciate it.

**Comment by tobimori** [comment]
No problem!

**Comment by styxlab** [comment]
@tobimori: I have nothing to add - you are always to the point! Thanks for answering!
