### ISSUE TITLE
Is there  any plan make a gatsby-theme-LIEBLING ?

### ISSUE THREAD

**Issue by xiyizhou** [styxlab/gatsby-theme-try-ghost#77]
the ghost-theme-LIEBLING is [here](https://github.com/eddiesigner/liebling/).

**Comment by tobimori** [comment]
@styxlab had the plan to add custom theme support, so that will follow, but rather in a time period > 6 months, cause we all got other stuff to do too.

**Comment by styxlab** [comment]
@xiyizhou: As @tobimori says, there are no immediate plans for new themes at the moment. However, if you or someone else wants to port that theme over to this project, I‘d be more than happy to help you with that. In this case, you should also involve the author of that theme.
