### ISSUE TITLE
Suggestion: Move out hardcoded strings to separate files

### ISSUE THREAD

**Issue by LukasJokubas** [styxlab/gatsby-theme-try-ghost#84]
Hi,

first of all, I wanted to let you know that I think you are doing an amazing job with this theme so far, it is exactly what I was looking for.

That being said, I am building a non-English site using your starter and I'm forced to shadow many of the components simply to translate the hardcoded english text strings inside. Could you please move those hard coded strings to a separate file, let's say strings.json so I only need to shadow that?

Also, I am looking to add a image zoom capability to the theme, I think something like this https://github.com/francoischalifour/medium-zoom would make a great addition to the list of theme plugins.

**Comment by styxlab** [comment]
@LukasJokubas: Thanks a lot for your support :smile:

It's a good idea to separate hard-coded text into a file, and shadowing is really not intended for this use case. Could you please help me by listing all the locations with hard coded texts?

Yeah, an image zoom plugin would be awesome. Just let me know what you need from my side, to get you started.

**Comment by LukasJokubas** [comment]
Files where I found static strings:
- components/common/AuthorList.js
- components/common/HeaderAuthor.js
- components/common/HeaderTag.js
- components/common/Layout.js
- components/common/Pagination.js
- components/common/PreviewPosts.js
- pages/404.js
- gatsby-theme-ghost-dark-mode/src/components/common/DarkModeToggle.js (button title attribute value)
- gatsby-theme-ghost-toc/src/components/common/TableOfContents.js
- gatsby-theme-ghost-members/src/components/common/Subscribe.js
- gatsby-theme-ghost-members/src/components/common/SubscribeButton.js
- gatsby-theme-ghost-members/src/components/common/SubscribeForm.js
- gatsby-theme-ghost-members/src/components/common/SubscribeOverlay.js
- @tryghost/helpers/lib/reading-time.js

**Comment by styxlab** [comment]
@LukasJokubas: I just finished the implementation and updated all packages. As you can see from the merge, there is a `lang.js` file in the `src/utils` directory, with the following structure:
```js
const lang = {
  en: {
    A_COLLECTION_OF: `A collection of`,
    BY_THIS_AUTHOR: `by this author`,
    ...
  },
}
```
Please do not shadow this file, rather add your language to it. The language used during compile can be selected in `siteConfig.js` with a new `locale` flag.

I also wrote a small helper function for selecting the texts (see `src/utils/use-lang.js`). This function ensures that you get a build time error, if you select a text that is not present in the language file. So, you can always be assured that a successful build contains all texts!

You may want to override the locale setting programmeticaly. This is also possible by calling the `useLang` function with an argument, such as `useLang('en')`. 

Also note the use in plugins: Every plugin should get it's own copy of `src/utils/use-lang.js` and a plugin specific `lang.js` file, that way the core project stays independent of plugin authors.

Finally: Please contribute your language files to this project. Just open a PR or send it directly to me for inclusion.

P.S.: Looking forward to the image zoom plugin!

**Comment by styxlab** [comment]
**UPDATE**: I removed the `locale` flag in `siteConfig.js` as we already have the `lang` property from the Ghost settings. Therefore, language is now taken from the settings in the Ghost Admin panel under *General Settings -> Publication Language`.

**Comment by LukasJokubas** [comment]
@styxlab thanks for getting to this so quickly.

I do have a few observations though:

**SubscribeForm.js** and **SubscribeOverlay.js**
- Value for the <HiddenLabel for="email"> should probably be translatable as well
- It would be nice to have variables like {site.title} directly in lang.js so it could be put at the begining of the sentence

**HeaderTag.js**
Some languages require 3 strings displayed for different ranges of post counts.

Example: A total of {n} posts:
Viso {n} įrašas   n -> 1, 21, 31, 41...
Viso {n} įrašai n -> 2,3,4,5,6,7,8,9,22,23,24,25,26,27,28,29,32,33,34,...
Viso {n} įrašų  (en: posts)  n -> 0,10,11,12,13,14,15,16,17,18,19,20,30,40,50...

**PreviewPosts.js**
Example: See all {n} posts
Žiūrėti visus {n} įrašą    n -> 21, 31, 41...
Žiūrėti visus {n} įrašus  n -> 2,3,4,5,6,7,8,9,22,23,24,25,26,27,28,29,32,33,34,...
Žiūrėti visus {n} įrašų   n -> 10,11,12,13,14,15,16,17,18,19,20,30,40,50...

**HeaderAuthor.js**
String "Website" should be translatable

**AuthorList.js**
String "by" should be translatable

**Layout.js**
Latest posts link could use Gatsby <Link> as it is internal link.
Would be nice to be able to control footer links in siteConfig.js

**PostCard.js**
Excerpt should be truncated, because when excerpt is missing in Ghost, first paragraph is pulled in, or even worse, if the first content card in ghost is HTML containing a long text, all of it gets pulled in.
Would be nice to be able to disable displaying of post authors in siteConfig.js

Thanks a lot for your help, I will send over my lang files when finished.

**Comment by styxlab** [comment]
I've implemented most of your suggestions, except:

-  3 strings in `HeaderTag.js` and `PreviewPosts.js` (this would require injecting calc functions)
- control footer links in `siteConfig.js` (can be done)
- excerpt should be truncated (it is already truncated, but only if given)
- disable displaying of post authors in siteConfig.js (I do not want to deviate roo much from Casper original theme, but an option would be fine)

Note that the `text()` function now contains a second parameter, which is a default text. I made use of it for the site title: If not defined in `lang.js` the standard `site.title` is displayed, but you can override the title by adding a `SITE_TITLE` entry in `lang.js`. I also added a second language to the `lang.js` file.

These are all great suggestions, so if you want to implement the ones that I missed out, you are more than welcome to issue a PR!

**Comment by styxlab** [comment]
Closing as delivered. Can always  reopen, if needed.
