### ISSUE TITLE
CSS clash with Commento

### ISSUE THREAD

**Issue by Prinz** [styxlab/gatsby-theme-try-ghost#85]
In `screen.css`:
```
.post-full-content pre {
    padding: 20px;
}
```
This padding affects any `<pre>` tags in Commento, so you get something like this:
![image](https://user-images.githubusercontent.com/32435499/82956226-42aa4a80-9fa8-11ea-982a-0db26e6d76e7.png)

On a side note, since Commento injects HTML into a source, should they have scoped their CSS or was it intentional to allow the user's CSS to apply to comments as well?

**Comment by styxlab** [comment]
I think commento CSS should not rely on global styles, so it has to be fixed there. Will look into this further once I get around it. If you have a solution/workaround let me know.

**Comment by Prinz** [comment]
I have a workaround, but it's more of a hack really, I just gave the `pre` elements their own CSS so they wouldn't inherit from screen.css like so 
```css
.commento-root .commento-markdown-help tr td pre {
    padding: unset;
}
```

**Comment by styxlab** [comment]
@Prinz: I found a proper fix by removing a class attribute that I accidentally added to the commento section. Fix is included in the latest package files.
