### ISSUE TITLE
Adding Subscription Like Lyra Theme On Ghost

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#87]
Adding Subscription Like Lyra Theme On Ghost , Is this possible ?

**Comment by amaljithev** [comment]
Any plan to convert into Lyra skin instead of Casper ? Lyra is basically an extension to Casper with paid membership functionality

**Comment by styxlab** [comment]
This is possible, but not on the priority list of this project at the moment.

**Comment by amaljithev** [comment]
@styxlab Thanks for the consideration. It would be nice if its happening.

https://github.com/TryGhost/Lyra
https://lyra.ghost.io/

**Comment by styxlab** [comment]
If you discovered the subscription feature that I added just yesterday, you can already observe how it integrates with the Ghost membership back-end.

I am fully aware of Lyra, which would be the the next step in that direction. I can help you or anyone else with porting Lyra to this project, but can't do it myself in the foreseeable future.

Just one question: How many times did you pay for content on a blog page so far?

**Comment by amaljithev** [comment]
@styxlab How many times did you pay for content on a blog page so far? : Well very rare , But i didnt came across any mindblowing blog contents which is worth paying for . Thank you @styxlab for considering this request

**Comment by styxlab** [comment]
To summarize: This is not on the agenda right now, but I would definitely support a contribution.

**Comment by amaljithev** [comment]
Any plans in porting to lyra ?

**Comment by styxlab** [comment]
No, not at the moment.
