### ISSUE TITLE
Define a CDN from which images do not get processed

### ISSUE THREAD

**Issue by savyajha** [styxlab/gatsby-theme-try-ghost#97]
Hi,

I've been using Ghost with the Cloudinary plugin, and I'd like to switch to using this project. However, I've found that it processes images from Cloudinary and stores them as well. Is it possible to get gatsby to _not_ process images coming from a particular domain? Or to not process images at all?

Because if I try to disable the `gatsby-plugin-ghost-images` then the entire build stops working.

Thanks

**Comment by styxlab** [comment]
This project should build, if you disable the `gatsby-plugin-ghost-images` plugin. To disable:
- remove the plugin from `gatsby-config.js`
- make sure the plugin is removed from node  modules: yarn remove `gatsby-plugin-ghost-images`

If you still get errors, please provide a link to the logs.

**Comment by savyajha** [comment]
I'm still getting an error. Just to clarify what I did:

- Used the starter project, added my own Ghost API key and all that
- `cd <project-directory>`
- `yarn`
- `cd node_modules/gatsby-theme-try-ghost`
- `yarn remove gatsby-plugin-ghost-images`
- Set `disable: true` in the theme's `gatsby-config.js`
- `cd ../..`
- `gatsby develop`

And it still doesn't work. Here are the logs: http://ix.io/2nLE

**Comment by styxlab** [comment]
@savyajha: Sorry was on the wrong page. Unfortunately the plugin is currently too tightly coupled to the core and removing it doesn't work. I once started implementing a `disable` option, but this is not yet finished.

This option will be implemented, but is currently not prioritized so it may take a long time until finished. If you want to dig into the problem (you'll have to write custom GraphQL resolvers) and fix it, I'm always happy to take PRs!

**Comment by savyajha** [comment]
Given I'm hardly a developer (I'm merely a tinkerer) and I've never worked with web tech before, I'm going to think long and hard about your offer to write PRs and then (probably) not do much. But thank you very much for your answer. I enjoy using this theme and defeinitely look forward to its continued development.

I'll close this issue then, if you don't mind.

**Comment by styxlab** [comment]
As I was looking at this already, I will add an option to this project, so you can disable in-sourcing images for Gatsby image processing.

**Comment by styxlab** [comment]
As I was already at it, I will implement an option to disable gatsby images soon.

**Comment by styxlab** [comment]
There is now a new option in `siteConfig.js` called `gatsbyImages`. Default is true. Set it to false, if you want to disable gatsby images.

**Comment by savyajha** [comment]
Thank you. I've tried it out, and it works. Thank you.

**Comment by styxlab** [comment]
You are very welcome.
