### ISSUE TITLE
Table Of Contents , Appearing over images

### ISSUE THREAD

**Issue by amaljithev** [styxlab/gatsby-theme-try-ghost#99]
![Screenshot_2020-05-30 Routing with Jamify](https://user-images.githubusercontent.com/33357428/83332151-40513480-a2b7-11ea-8915-f22d9e4c3a0a.png)

@styxlab Table of content in jamify looks great, But there are few issues like TOC appearing on top images. Also is it possible to give an option to hide/show, So that it won't distract people reading the posts .

**Comment by styxlab** [comment]
@amaljithev This is intended behaviour. The ToC is only shown on the side for large screens. If you make the width of your window smaller, the ToC will automatically move to the top of the article. You can use that feature to hide the ToC. I personally like the ToC to be always on top, but that may be a matter of taste. The ToC is inspired from Gastby and they also do not see the need for a show/hide toggle.

**Comment by styxlab** [comment]
I tested with different variants and I think you are right in that the wide gallery images should overlap the ToC. The post content is locally more important than the ToC. I will change that in the next version. Thanks for noting.
